const M=[['CHI','CAR'],['TB','CIN'],['NO','DET'],['BUF','HOU'],['BAL','IND'],['CLE','JAX'],['ATL','PIT'],['NYJ','TEN'],['ARI','LAC'],['MIA','LV'],['GB','MIN'],['WAS','PHI'],['DAL','NYG'],['DEN','KC']];
const N={1:'CHI',2:'CAR',3:'TB',4:'CIN',5:'NO',6:'DET',7:'BUF',8:'HOU',9:'BAL',10:'IND',11:'CLE',12:'JAX',13:'ATL',14:'PIT',15:'NYJ',16:'TEN',17:'ARI',18:'LAC',19:'MIA',20:'LV',21:'GB',22:'MIN',23:'WAS',24:'PHI',25:'DAL',26:'NYG',27:'DEN',28:'KC'};
const P=[['D.C.',[1,4,6,8,9,12,14,15,18,20,22,24,25,27],48],['JC',[1,4,6,7,9,12,14,15,18,19,22,24,26,28],52],['DJS',[1,4,6,8,9,12,14,16,18,20,21,24,25,27],40],['Thaddeus',[1,4,6,7,10,12,13,15,18,20,22,24,26,28],45]].map(([name,nums,mnf])=>({name,nums,mnf,picks:nums.map(n=>N[n])}));
const C={CHI:'#0B162A',CAR:'#0085CA',TB:'#D50A0A',CIN:'#FB4F14',NO:'#B3995D',DET:'#0076B6',BUF:'#00338D',HOU:'#03202F',BAL:'#241773',IND:'#002C5F',CLE:'#311D00',JAX:'#006778',ATL:'#A71930',PIT:'#FFB612',NYJ:'#125740',TEN:'#4B92DB',ARI:'#97233F',LAC:'#0080C6',MIA:'#008E97',LV:'#111',GB:'#203731',MIN:'#4F2683',WAS:'#5A1414',PHI:'#004C54',DAL:'#003594',NYG:'#0B2265',DEN:'#FB4F14',KC:'#E31837'};
const D=M.map((_,i)=>i===13?'20260914':'20260913'),A={JAC:'JAX',WSH:'WAS'},PROXY='https://txbrowtmemwldywdpgiy.supabase.co/functions/v1/nfl-pool-scores';
let G=M.map(([away,home])=>({away,home,state:'pre',completed:false,winner:null,awayScore:null,homeScore:null,detail:'Scheduled',eventId:null})),gen=0,ctl=null,lastFetchedAt=null;
const $=id=>document.getElementById(id),norm=x=>A[x]||x,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),score=x=>{let n;if(typeof x==='string'){const v=x.trim();if(!v||!/^\d+$/.test(v))return null;n=Number(v)}else if(typeof x==='number')n=x;else return null;return Number.isFinite(n)&&Number.isInteger(n)&&n>=0?n:null};
function stats(p,games=G){let w=0,l=0,left=0;games.forEach((g,i)=>{if(g.completed){if(g.winner)p.picks[i]===g.winner?w++:l++}else left++});return{w,l,left}}
function mnf(games=G){const g=games[13],a=score(g.awayScore),h=score(g.homeScore),ok=a!==null&&h!==null;return{final:!!(g.completed&&ok),total:ok&&(g.state==='in'||g.completed)?a+h:null}}
function rows(games=G){const t=mnf(games);return P.map((p,i)=>({...p,...stats(p,games),diff:t.final?Math.abs(p.mnf-t.total):null,i})).sort((a,b)=>b.w-a.w||a.l-b.l||(t.final?a.diff-b.diff:0)||a.i-b.i)}
function topIndices(wins,t=mnf()){const best=Math.max(...wins);let leaders=wins.map((w,i)=>w===best?i:-1).filter(i=>i>=0);if(t.final&&leaders.length>1){const bestDiff=Math.min(...leaders.map(i=>Math.abs(P[i].mnf-t.total)));leaders=leaders.filter(i=>Math.abs(P[i].mnf-t.total)===bestDiff)}return leaders}
function tiedWith(a,b,t=mnf()){return a.w===b.w&&a.l===b.l&&(!t.final||a.diff===b.diff)}
function state(g){return g.completed?(g.winner?'FINAL':'FINAL TIE'):g.state==='in'?(g.detail||'LIVE'):(g.detail||'SCHEDULED')}
function badge(t){return`<span class="badge" style="--tc:${C[t]||'#33465f'}">${t}</span>`}
function swingIndexes(unfinishedOnly=false,games=G){return M.map((_,i)=>i).filter(i=>new Set(P.map(p=>p.picks[i])).size>1&&(!unfinishedOnly||!games[i].completed))}
function raceStatus(games=G){const unfinished=games.map((g,i)=>!g.completed?i:-1).filter(i=>i>=0),swings=swingIndexes(true,games),base=P.map(p=>stats(p,games).w),t=mnf(games),ceiling=base.map(w=>w+unfinished.length);if(!unfinished.length){const winners=topIndices(base,t),co=winners.length>1;return{outcomes:1,racePaths:1,items:P.map((p,i)=>({name:p.name,status:winners.includes(i)?'WINNER':'OUT',ceiling:base[i],roots:[],topPaths:winners.includes(i)?1:0,note:winners.includes(i)?(co?'Co-winner · exact tiebreak tied':'Pool winner'):'Slate complete'}))}}
const total=3**swings.length,canTop=Array(P.length).fill(false),clinched=Array(P.length).fill(true),topPaths=Array(P.length).fill(0);for(let path=0;path<total;path++){const wins=base.slice();let code=path;for(const gi of swings){const outcome=code%3;code=Math.floor(code/3);if(outcome<2){const winner=outcome===0?M[gi][0]:M[gi][1];P.forEach((p,pi)=>{if(p.picks[gi]===winner)wins[pi]++})}}const leaders=topIndices(wins,t);leaders.forEach(pi=>{canTop[pi]=true;topPaths[pi]++});for(let pi=0;pi<P.length;pi++)if(!(leaders.length===1&&leaders[0]===pi))clinched[pi]=false}
const contenders=P.map((_,i)=>canTop[i]?i:-1).filter(i=>i>=0),activeSwings=swings.filter(gi=>new Set(contenders.map(pi=>P[pi].picks[gi])).size>1),racePaths=3**activeSwings.length,outcomes=3**unfinished.length;return{outcomes,racePaths,items:P.map((p,i)=>{const status=clinched[i]?'CLINCHED':canTop[i]?'ALIVE':'OUT',roots=status==='OUT'?[]:activeSwings.map(gi=>p.picks[gi]);return{name:p.name,status,ceiling:ceiling[i],roots,topPaths:topPaths[i],note:status==='CLINCHED'?'Sole pool win guaranteed':status==='OUT'?'Cannot finish first':`Ceiling ${ceiling[i]} wins`}})}}
function renderRace(race){$('scenarioCount').textContent=race.outcomes===1?'Final':`${race.outcomes.toLocaleString()} outcomes · ${race.racePaths.toLocaleString()} race paths`;$('raceList').innerHTML=race.items.map(x=>`<div class="race-row"><div class="race-copy"><div class="race-name">${esc(x.name)}</div><div class="race-sub">${esc(x.note)}</div></div><span class="status-pill ${x.status.toLowerCase()}">${x.status}</span><div class="rooting">${x.roots.length?x.roots.map(t=>`<span class="root-chip">${t}</span>`).join(''):'<span class="race-sub">—</span>'}</div></div>`).join('')}
function simulateGame(games,i,winner){return games.map((g,gi)=>gi===i?{...g,state:'post',completed:true,winner:winner||null,awayScore:null,homeScore:null,detail:winner?'Simulated final':'Simulated tie'}:{...g})}
function impactText(i,winner,baseRace){const sim=raceStatus(simulateGame(G,i,winner)),before=new Map(baseRace.items.map(x=>[x.name,x.status])),after=new Map(sim.items.map(x=>[x.name,x.status])),clinched=P.filter(p=>['CLINCHED','WINNER'].includes(after.get(p.name))&&!['CLINCHED','WINNER'].includes(before.get(p.name))).map(p=>p.name),out=P.filter(p=>after.get(p.name)==='OUT'&&before.get(p.name)!=='OUT').map(p=>p.name);if(clinched.length)return`clinches ${clinched.join(', ')}`;if(out.length)return`eliminates ${out.join(', ')}`;const active=baseRace.items.filter(x=>x.status!=='OUT').map(x=>x.name);if(!winner)return active.length?`0 pts to all · ${active.length} contender${active.length===1?'':'s'} remain`:'0 pts to all';const helps=P.filter(p=>active.includes(p.name)&&p.picks[i]===winner).map(p=>p.name),hurts=P.filter(p=>active.includes(p.name)&&p.picks[i]!==winner).map(p=>p.name);return helps.length&&hurts.length?`helps ${helps.join(', ')} · hurts ${hurts.join(', ')}`:helps.length?`helps ${helps.join(', ')} · no active counterpick`:'no active-race leverage'}
function pickerNames(i,team,race){const status=new Map(race.items.map(x=>[x.name,x.status]));return P.filter(p=>p.picks[i]===team).map(p=>status.get(p.name)==='OUT'?`<span class="picker eliminated">${esc(p.name)} · OUT</span>`:`<span class="picker">${esc(p.name)}</span>`).join('<span class="sep"> · </span>')}
function renderSwings(race){const ids=swingIndexes(true);$('swingMeta').textContent=`${ids.length} left`;$('swingLeft').textContent=ids.length;if(!ids.length){$('swingList').innerHTML='<div class="empty">No swing games remain. The race is decided by finalized results and, if needed, the MNF tiebreak.</div>';return}$('swingList').innerHTML=ids.map(i=>{const g=G[i],show=g.state==='in',as=score(g.awayScore),hs=score(g.homeScore);return`<div class="swing-item"><div class="swing-side"><div class="swing-team">${badge(g.away)} ${g.away}</div><div class="pickers">${pickerNames(i,g.away,race)}</div></div><div class="swing-mid"><div class="swing-state">${esc(state(g))}</div><div class="swing-score">${show?`${as??'—'}–${hs??'—'}`:'vs'}</div></div><div class="swing-side home"><div class="swing-team">${g.home} ${badge(g.home)}</div><div class="pickers">${pickerNames(i,g.home,race)}</div></div><div class="impact-grid"><div class="impact"><b>${g.away}</b> ${esc(impactText(i,g.away,race))}</div><div class="impact"><b>${g.home}</b> ${esc(impactText(i,g.home,race))}</div><div class="impact tie-impact"><b>TIE</b> ${esc(impactText(i,null,race))}</div></div></div>`}).join('')}
function gameOrder(){const rank=g=>g.state==='in'?0:!g.completed?1:2;return G.map((g,i)=>({g,i})).sort((a,b)=>rank(a.g)-rank(b.g)||a.i-b.i)}
function render(){const r=rows(),lead=r[0],f=G.filter(g=>g.completed).length,live=G.filter(g=>g.state==='in'&&!g.completed).length,t=mnf(),finalWinners=f===14?topIndices(P.map(p=>stats(p).w),t):[],race=raceStatus();let rank=1;$('standings').innerHTML=r.map((p,i)=>{if(i&&!tiedWith(p,r[i-1],t))rank=i+1;const leadTie=tiedWith(p,lead,t);return`<tr class="${leadTie?'leadrow':''}"><td>${rank}</td><td class="entry">${esc(p.name)}</td><td class="c w">${p.w}</td><td class="c l">${p.l}</td><td class="c">${p.left}</td><td class="c hide">${p.mnf}</td><td class="c">${p.diff??'—'}</td></tr>`}).join('');$('gamegrid').innerHTML=gameOrder().map(({g})=>{const show=g.state==='in'||g.completed,cl=g.completed?(g.winner?'final':'final tie'):g.state==='in'?'live':'pre',as=score(g.awayScore),hs=score(g.homeScore);return`<div class="game ${cl}"><div class="team ${g.winner===g.away?'winner':''}">${badge(g.away)}<span class="abbr">${g.away}</span>${show?`<span class="score">${as??'—'}</span>`:''}</div><div class="status">${esc(state(g))}</div><div class="team home ${g.winner===g.home?'winner':''}">${show?`<span class="score">${hs??'—'}</span>`:''}<span class="abbr">${g.home}</span>${badge(g.home)}</div></div>`}).join('');$('pickHead').innerHTML='<tr><th class="name">Entry</th>'+M.map(([a,h])=>`<th class="c">${a}/${h}</th>`).join('')+'</tr>';$('pickBody').innerHTML=P.map(p=>'<tr><td class="name">'+esc(p.name)+'</td>'+p.picks.map((pick,i)=>{const g=G[i],done=g.completed,ok=done&&g.winner&&pick===g.winner,tie=done&&!g.winner;return`<td class="c ${tie?'neutral':done?(ok?'ok':'bad'):'pending'}">${pick}${tie?' · 0':done?(ok?' ✓':' ✕'):''}</td>`}).join('')+'</tr>').join('');$('finals').textContent=`${f}/14`;$('liveCount').textContent=live;$('left').textContent=14-f;$('mnf').textContent=t.total==null?'—':t.total+(t.final?'':'*');if(f===14&&finalWinners.length>1){$('leaderName').textContent=finalWinners.map(i=>P[i].name).join(' / ');$('leaderRecord').textContent=`${lead.w}–${lead.l}`;$('leaderKicker').textContent='Co-winners';$('leaderNote').textContent='Exact MNF tiebreak is tied; no secondary tiebreak is defined.'}else{$('leaderName').textContent=lead?.name||'—';$('leaderRecord').textContent=lead?`${lead.w}–${lead.l}`:'0–0';$('leaderKicker').textContent=f===14?'Pool winner':'Current leader';const ties=lead?r.filter(x=>tiedWith(x,lead,t)).length:0;$('leaderNote').textContent=ties>1&&!t.final?`${ties} entries are tied. MNF total remains reserved for the final tiebreaker.`:`${f} of 14 games are final.`}$('bestWins').textContent=lead?.w??0;const pc=Math.round(f/14*100);$('progressText').textContent=`${pc}%`;$('progressBar').style.width=`${pc}%`;$('tbNote').textContent=t.final?`MNF final total: ${t.total}. Tiebreak differences are active.`:'MNF guesses: D.C. 48 · JC 52 · DJS 40 · Thaddeus 45.';renderRace(race);renderSwings(race)}
function warn(list){const e=$('error');e.replaceChildren();if(!list.length)return;const b=document.createElement('div');b.className='error';b.textContent=`Some feed data was ignored to protect standings: ${list.join(' · ')}`;e.appendChild(b)}
function parseEvent(e,a,h,old){const c=e?.competitions?.[0],away=c?.competitors?.find(x=>x.homeAway==='away'),home=c?.competitors?.find(x=>x.homeAway==='home');if(!away||!home)return{game:old,warning:`${a}-${h}: missing competitor data`};const st=e.status?.type?.state||'pre',done=e.status?.type?.completed===true,as=score(away.score),hs=score(home.score);if((st==='in'||done)&&(as===null||hs===null))return{game:old,warning:`${a}-${h}: invalid score ignored`};const tied=done&&as===hs;return{game:{away:a,home:h,state:st,completed:done,winner:done&&!tied?(as>hs?a:h):null,awayScore:as,homeScore:hs,detail:String(e.status?.type?.shortDetail||e.status?.type?.detail||(done?(tied?'Final · Tie':'Final'):'Scheduled')),eventId:e.id?String(e.id):old.eventId},warning:null}}
function select(items,a,h,date,old){const q=items.filter(({event,sourceDate})=>{if(sourceDate!==date)return false;const c=event?.competitions?.[0],x=c?.competitors?.find(v=>v.homeAway==='away'),y=c?.competitors?.find(v=>v.homeAway==='home');if(norm(x?.team?.abbreviation)!==a||norm(y?.team?.abbreviation)!==h)return false;const s=event?.season?.type,w=event?.week?.number;if(s!=null&&Number(s)!==2)return false;if(w!=null&&Number(w)!==1)return false;return true});if(!q.length)return{event:null,warning:null};if(q.length!==1)return{event:null,warning:`${a}-${h}: duplicate events ignored`};const e=q[0].event;if(old.eventId&&e.id&&String(e.id)!==String(old.eventId))return{event:null,warning:`${a}-${h}: event identity changed`};return{event:e,warning:null}}
function ageSeconds(ts){const ms=Date.parse(ts);if(!Number.isFinite(ms))return null;const delta=Date.now()-ms;if(delta<-60000)return null;return Math.max(0,Math.floor(delta/1000))}
function setSync(fetchedAt,warnings=[]){lastFetchedAt=typeof fetchedAt==='string'?fetchedAt:null;const age=ageSeconds(lastFetchedAt),delayed=age===null||age>30,label=delayed?'DELAYED':'LIVE',ageText=age===null?'age unknown':`data ${age}s old`;$('sync').textContent=`${label} · ${ageText}${warnings.length?` · ${warnings.length} warning${warnings.length===1?'':'s'}`:''}`;$('dot').style.background=warnings.length||delayed?'var(--gold)':'var(--green)'}
async function feed(signal){const r=await fetch(`${PROXY}?t=${Date.now()}`,{signal,cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`proxy ${r.status}`);const j=await r.json();if(!j||!Array.isArray(j.days))throw new Error('invalid proxy payload');return j}
async function update(){const id=++gen;if(ctl)ctl.abort();const c=new AbortController;ctl=c;$('refresh').disabled=true;$('sync').textContent='Updating…';try{const j=await feed(c.signal);if(id!==gen)return;const items=[];for(const d of j.days||[])for(const event of Array.isArray(d?.events)?d.events:[])items.push({event,sourceDate:String(d.date||'')});const warnings=[],next=M.map(([a,h],i)=>{const s=select(items,a,h,D[i],G[i]);if(s.warning)warnings.push(s.warning);if(!s.event)return G[i];const p=parseEvent(s.event,a,h,G[i]);if(p.warning)warnings.push(p.warning);return p.game});if(id!==gen)return;G=next;render();warn(warnings);setSync(j.fetchedAt,warnings)}catch(e){if(e?.name==='AbortError'||id!==gen)return;$('sync').textContent=lastFetchedAt?`FEED UNAVAILABLE · last good ${ageSeconds(lastFetchedAt)??'?'}s ago`:'FEED UNAVAILABLE';$('dot').style.background='var(--red)';warn(['Automatic score refresh failed. Existing results are preserved; tap REFRESH to retry.'])}finally{if(id===gen){$('refresh').disabled=false;if(ctl===c)ctl=null}}}
$('refresh').addEventListener('click',update);render();update();setInterval(update,20000);
