const M=[['CHI','CAR'],['TB','CIN'],['NO','DET'],['BUF','HOU'],['BAL','IND'],['CLE','JAX'],['ATL','PIT'],['NYJ','TEN'],['ARI','LAC'],['MIA','LV'],['GB','MIN'],['WAS','PHI'],['DAL','NYG'],['DEN','KC']];
const N={1:'CHI',2:'CAR',3:'TB',4:'CIN',5:'NO',6:'DET',7:'BUF',8:'HOU',9:'BAL',10:'IND',11:'CLE',12:'JAX',13:'ATL',14:'PIT',15:'NYJ',16:'TEN',17:'ARI',18:'LAC',19:'MIA',20:'LV',21:'GB',22:'MIN',23:'WAS',24:'PHI',25:'DAL',26:'NYG',27:'DEN',28:'KC'};
const P=[['D.C.',[1,4,6,8,9,12,14,15,18,20,22,24,25,27],48],['JC',[1,4,6,7,9,12,14,15,18,19,22,24,26,28],52],['DJS',[1,4,6,8,9,12,14,16,18,20,21,24,25,27],40],['Thaddeus',[1,4,6,7,10,12,13,15,18,20,22,24,26,28],45]].map(([name,nums,mnf])=>({name,nums,mnf,picks:nums.map(n=>N[n])}));
const C={CHI:'#0B162A',CAR:'#0085CA',TB:'#D50A0A',CIN:'#FB4F14',NO:'#B3995D',DET:'#0076B6',BUF:'#00338D',HOU:'#03202F',BAL:'#241773',IND:'#002C5F',CLE:'#311D00',JAX:'#006778',ATL:'#A71930',PIT:'#FFB612',NYJ:'#125740',TEN:'#4B92DB',ARI:'#97233F',LAC:'#0080C6',MIA:'#008E97',LV:'#111',GB:'#203731',MIN:'#4F2683',WAS:'#5A1414',PHI:'#004C54',DAL:'#003594',NYG:'#0B2265',DEN:'#FB4F14',KC:'#E31837'};
const D=M.map((_,i)=>i===13?'20260914':'20260913'),A={JAC:'JAX',WSH:'WAS'},PROXY='https://txbrowtmemwldywdpgiy.supabase.co/functions/v1/nfl-pool-scores';
let G=M.map(([away,home])=>({away,home,state:'pre',completed:false,winner:null,awayScore:null,homeScore:null,detail:'Scheduled',eventId:null})),gen=0,ctl=null;
const $=id=>document.getElementById(id),norm=x=>A[x]||x,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),score=x=>{if(x===null||x===undefined||x==='')return null;const n=Number(x);return Number.isFinite(n)&&Number.isInteger(n)&&n>=0?n:null};
function stats(p){let w=0,l=0,left=0;G.forEach((g,i)=>{if(g.completed&&g.winner)p.picks[i]===g.winner?w++:l++;else left++});return{w,l,left}}
function mnf(){const g=G[13],a=score(g.awayScore),h=score(g.homeScore),ok=a!==null&&h!==null;return{final:!!(g.completed&&g.winner&&ok),total:ok&&(g.state==='in'||g.completed)?a+h:null}}
function rows(){const t=mnf();return P.map((p,i)=>({...p,...stats(p),diff:t.final?Math.abs(p.mnf-t.total):null,i})).sort((a,b)=>b.w-a.w||a.l-b.l||(t.final?a.diff-b.diff:0)||a.i-b.i)}
function state(g){return g.completed?'FINAL':g.state==='in'?(g.detail||'LIVE'):(g.detail||'SCHEDULED')}
function badge(t){return`<span class="badge" style="--tc:${C[t]||'#33465f'}">${t}</span>`}
function swingIndexes(unfinishedOnly=false){return M.map((_,i)=>i).filter(i=>new Set(P.map(p=>p.picks[i])).size>1&&(!unfinishedOnly||!(G[i].completed&&G[i].winner)))}
function raceStatus(){const unfinished=G.map((g,i)=>!(g.completed&&g.winner)?i:-1).filter(i=>i>=0),base=P.map(p=>stats(p).w);if(!unfinished.length){const finalRows=rows(),winner=finalRows[0]?.name;return{scenarios:1,items:P.map((p,i)=>({name:p.name,status:p.name===winner?'WINNER':'FINAL',ceiling:base[i],roots:[],note:p.name===winner?'Pool winner':'Slate complete'}))}}
const total=2**unfinished.length,canTop=Array(P.length).fill(false),clinched=Array(P.length).fill(true),ceiling=base.slice();for(let mask=0;mask<total;mask++){const wins=base.slice();unfinished.forEach((gi,bit)=>{const winner=(mask>>bit)&1?M[gi][1]:M[gi][0];P.forEach((p,pi)=>{if(p.picks[gi]===winner)wins[pi]++})});const best=Math.max(...wins),topCount=wins.filter(x=>x===best).length;wins.forEach((w,pi)=>{ceiling[pi]=Math.max(ceiling[pi],w);if(w===best)canTop[pi]=true;if(!(w===best&&topCount===1))clinched[pi]=false})}
const swings=swingIndexes(true);return{scenarios:total,items:P.map((p,i)=>{const status=clinched[i]?'CLINCHED':canTop[i]?'ALIVE':'OUT',roots=status==='OUT'?[]:swings.map(gi=>p.picks[gi]);return{name:p.name,status,ceiling:ceiling[i],roots,note:status==='CLINCHED'?'Top record guaranteed':status==='OUT'?'Cannot reach top record':`Ceiling ${ceiling[i]} wins`}})}}
function renderRace(){const race=raceStatus();$('scenarioCount').textContent=race.scenarios===1?'Final':`${race.scenarios.toLocaleString()} paths`;$('raceList').innerHTML=race.items.map(x=>`<div class="race-row"><div class="race-copy"><div class="race-name">${esc(x.name)}</div><div class="race-sub">${esc(x.note)}</div></div><span class="status-pill ${x.status.toLowerCase()}">${x.status}</span><div class="rooting">${x.roots.length?x.roots.map(t=>`<span class="root-chip">${t}</span>`).join(''):'<span class="race-sub">—</span>'}</div></div>`).join('')}
function renderSwings(){const ids=swingIndexes(true);$('swingMeta').textContent=`${ids.length} left`;$('swingLeft').textContent=ids.length;if(!ids.length){$('swingList').innerHTML='<div class="empty">No swing games remain. The race is decided by finalized results and, if needed, the MNF tiebreak.</div>';return}$('swingList').innerHTML=ids.map(i=>{const g=G[i],away=P.filter(p=>p.picks[i]===g.away).map(p=>p.name),home=P.filter(p=>p.picks[i]===g.home).map(p=>p.name),show=g.state==='in',as=score(g.awayScore),hs=score(g.homeScore);return`<div class="swing-item"><div class="swing-side"><div class="swing-team">${badge(g.away)} ${g.away}</div><div class="pickers">${away.map(esc).join(' · ')}</div></div><div class="swing-mid"><div class="swing-state">${esc(state(g))}</div><div class="swing-score">${show?`${as??'—'}–${hs??'—'}`:'vs'}</div></div><div class="swing-side home"><div class="swing-team">${g.home} ${badge(g.home)}</div><div class="pickers">${home.map(esc).join(' · ')}</div></div></div>`}).join('')}
function render(){const r=rows(),lead=r[0],f=G.filter(g=>g.completed&&g.winner).length,live=G.filter(g=>g.state==='in').length,t=mnf();$('standings').innerHTML=r.map((p,i)=>`<tr class="${i?'':'leadrow'}"><td>${i+1}</td><td class="entry">${esc(p.name)}</td><td class="c w">${p.w}</td><td class="c l">${p.l}</td><td class="c">${p.left}</td><td class="c hide">${p.mnf}</td><td class="c">${p.diff??'—'}</td></tr>`).join('');$('gamegrid').innerHTML=G.map(g=>{const show=g.state==='in'||g.completed,cl=g.completed?'final':g.state==='in'?'live':'pre',as=score(g.awayScore),hs=score(g.homeScore);return`<div class="game ${cl}"><div class="team ${g.winner===g.away?'winner':''}">${badge(g.away)}<span class="abbr">${g.away}</span>${show?`<span class="score">${as??'—'}</span>`:''}</div><div class="status">${esc(state(g))}</div><div class="team home ${g.winner===g.home?'winner':''}">${show?`<span class="score">${hs??'—'}</span>`:''}<span class="abbr">${g.home}</span>${badge(g.home)}</div></div>`}).join('');$('pickHead').innerHTML='<tr><th class="name">Entry</th>'+M.map(([a,h])=>`<th class="c">${a}/${h}</th>`).join('')+'</tr>';$('pickBody').innerHTML=P.map(p=>'<tr><td class="name">'+esc(p.name)+'</td>'+p.picks.map((pick,i)=>{const g=G[i],done=g.completed&&g.winner,ok=done&&pick===g.winner;return`<td class="c ${done?(ok?'ok':'bad'):'pending'}">${pick}${done?(ok?' ✓':' ✕'):''}</td>`}).join('')+'</tr>').join('');$('finals').textContent=`${f}/14`;$('liveCount').textContent=live;$('left').textContent=14-f;$('mnf').textContent=t.total==null?'—':t.total+(t.final?'':'*');$('leaderName').textContent=lead?.name||'—';$('leaderRecord').textContent=lead?`${lead.w}–${lead.l}`:'0–0';$('leaderKicker').textContent=f===14?'Pool leader':'Current leader';const ties=lead?r.filter(x=>x.w===lead.w&&x.l===lead.l).length:0;$('leaderNote').textContent=ties>1&&!t.final?`${ties} entries are tied. MNF total remains reserved for the final tiebreaker.`:`${f} of 14 games are final.`;$('bestWins').textContent=lead?.w??0;const pc=Math.round(f/14*100);$('progressText').textContent=`${pc}%`;$('progressBar').style.width=`${pc}%`;$('tbNote').textContent=t.final?`MNF final total: ${t.total}. Tiebreak differences are active.`:'MNF guesses: D.C. 48 · JC 52 · DJS 40 · Thaddeus 45.';renderRace();renderSwings()}
function warn(list){const e=$('error');e.replaceChildren();if(!list.length)return;const b=document.createElement('div');b.className='error';b.textContent=`Some feed data was ignored to protect standings: ${list.join(' · ')}`;e.appendChild(b)}
function parseEvent(e,a,h,old){const c=e?.competitions?.[0],away=c?.competitors?.find(x=>x.homeAway==='away'),home=c?.competitors?.find(x=>x.homeAway==='home');if(!away||!home)return{game:old,warning:`${a}-${h}: missing competitor data`};const st=e.status?.type?.state||'pre',done=e.status?.type?.completed===true,as=score(away.score),hs=score(home.score);if((st==='in'||done)&&(as===null||hs===null))return{game:old,warning:`${a}-${h}: invalid score ignored`};if(done&&as===hs)return{game:old,warning:`${a}-${h}: tied final ignored`};return{game:{away:a,home:h,state:st,completed:done,winner:done?(as>hs?a:h):null,awayScore:as,homeScore:hs,detail:String(e.status?.type?.shortDetail||e.status?.type?.detail||(done?'Final':'Scheduled')),eventId:e.id?String(e.id):old.eventId},warning:null}}
function select(items,a,h,date,old){const q=items.filter(({event,sourceDate})=>{if(sourceDate!==date)return false;const c=event?.competitions?.[0],x=c?.competitors?.find(v=>v.homeAway==='away'),y=c?.competitors?.find(v=>v.homeAway==='home');if(norm(x?.team?.abbreviation)!==a||norm(y?.team?.abbreviation)!==h)return false;const s=event?.season?.type,w=event?.week?.number;if(s!=null&&Number(s)!==2)return false;if(w!=null&&Number(w)!==1)return false;return true});if(!q.length)return{event:null,warning:null};if(q.length!==1)return{event:null,warning:`${a}-${h}: duplicate events ignored`};const e=q[0].event;if(old.eventId&&e.id&&String(e.id)!==String(old.eventId))return{event:null,warning:`${a}-${h}: event identity changed`};return{event:e,warning:null}}
async function feed(signal){const r=await fetch(PROXY,{signal,cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`proxy ${r.status}`);const j=await r.json();if(!j||!Array.isArray(j.days))throw new Error('invalid proxy payload');return j}
async function update(){const id=++gen;if(ctl)ctl.abort();const c=new AbortController;ctl=c;$('refresh').disabled=true;$('sync').textContent='Updating…';try{const j=await feed(c.signal);if(id!==gen)return;const items=[];for(const d of j.days||[])for(const event of Array.isArray(d?.events)?d.events:[])items.push({event,sourceDate:String(d.date||'')});const warnings=[],next=M.map(([a,h],i)=>{const s=select(items,a,h,D[i],G[i]);if(s.warning)warnings.push(s.warning);if(!s.event)return G[i];const p=parseEvent(s.event,a,h,G[i]);if(p.warning)warnings.push(p.warning);return p.game});if(id!==gen)return;G=next;render();warn(warnings);$('sync').textContent=`LIVE · ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}${warnings.length?` · ${warnings.length} warning${warnings.length===1?'':'s'}`:''}`;$('dot').style.background=warnings.length?'var(--gold)':'var(--green)'}catch(e){if(e?.name==='AbortError'||id!==gen)return;$('sync').textContent='FEED UNAVAILABLE';$('dot').style.background='var(--red)';warn(['Automatic score refresh failed. Existing results are preserved; tap REFRESH to retry.'])}finally{if(id===gen){$('refresh').disabled=false;if(ctl===c)ctl=null}}}
$('refresh').addEventListener('click',update);render();update();setInterval(update,20000);
