// Writes dist/_headers, the response headers Netlify serves with the static files of a build, once scripts/build.mjs
// has written dist/ (netlify.toml runs the two in that order). The Content-Security-Policy is the one
// contentSecurityPolicy() derives from the built platform-config.js, read back by parseRuntimeConfig() exactly as
// scripts/serve.mjs reads it for the localhost gate, so a hosted page runs under the policy the local server sends:
// its own origin and this build's Data API origin (none for a sandbox), never Neon Auth. Nothing else is read: no
// environment variable and no proxy setting. The build's output is checked before anything is written, and anything
// unexpected is refused: a directory that is not exactly the build's files, a page or script that differs from the
// sources (a stale build), a configuration or SDK bundle the build could not have written, and an existing _headers,
// which is never overwritten. Same build, same bytes. Netlify applies _headers only to files it serves from its own
// store, never to a function's response, so the Auth proxy's answers keep the core's own headers
// (server/auth-proxy-core.mjs) and depend on nothing here.
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {APP_DIR,CONFIG_FILE,OUTPUT_FILES,SDK_FILE,STATIC_FILES,listFiles,verifySdkBundle} from './build.mjs';
import {contentSecurityPolicy,parseRuntimeConfig} from './runtime-config.mjs';

export const HEADERS_FILE='_headers';
// Netlify serves every site over HTTPS. One year, for this host only: includeSubDomains or preload would bind the
// commercial domain's other hosts, and preload is hard to reverse.
const HSTS='max-age=31536000';
// A host with a "neonauth" label, as every Neon Auth host has. The browser reaches Neon Auth only through the
// same-origin proxy, so the policy may never allow one.
const NEON_AUTH_HOST=/(?:\/\/|\.)neonauth\./i;

const sha256=body=>crypto.createHash('sha256').update(body).digest('hex');

// One rule for every path Netlify serves from the build: the pages, scripts, stylesheet, manifest and SDK bundle.
export function netlifyHeaders(config){
  const csp=contentSecurityPolicy(config);
  if(NEON_AUTH_HOST.test(csp))throw new Error('the Data API URL is on a Neon Auth host: the page must never be allowed to reach Neon Auth directly');
  return [
    `# Generated by scripts/netlify-headers.mjs from the ${config.mode} build's platform-config.js. Do not edit: rebuild instead.`,
    '/*',
    `  Content-Security-Policy: ${csp}`,
    '  X-Content-Type-Options: nosniff',
    '  Referrer-Policy: no-referrer',
    '  Cache-Control: no-cache',
    `  Strict-Transport-Security: ${HSTS}`,
    ''
  ].join('\n');
}

export function writeNetlifyHeaders({appDir=APP_DIR,dir}={}){
  appDir=path.resolve(appDir);
  dir=path.resolve(dir??path.join(appDir,'dist'));
  if(!fs.lstatSync(dir,{throwIfNoEntry:false})?.isDirectory())throw new Error(`${dir} is not a build directory: run npm run build first`);
  const file=path.join(dir,HEADERS_FILE);
  if(fs.lstatSync(file,{throwIfNoEntry:false}))throw new Error(`refusing to overwrite: ${dir} already holds ${HEADERS_FILE} (remove dist/ and build again)`);
  // Exactly the build's files: none missing, none added, and nothing that is not a regular file.
  const found=listFiles(dir);
  const problems=[...found.filter(name=>!OUTPUT_FILES.includes(name)).map(name=>`unexpected ${name}`),...OUTPUT_FILES.filter(name=>!found.includes(name)).map(name=>`missing ${name}`)];
  if(problems.length)throw new Error(`${dir} is not exactly the build's output: ${problems.join(', ')}`);
  // Built from these sources: a page, stylesheet or script from another build is stale.
  for(const name of STATIC_FILES){
    if(!fs.readFileSync(path.join(dir,name)).equals(fs.readFileSync(path.join(appDir,name))))throw new Error(`${name} differs from ${path.join(appDir,name)}: the build is stale, build again`);
  }
  // Values the build could have written, byte for byte, and the bundle it verifies.
  const config=parseRuntimeConfig(fs.readFileSync(path.join(dir,CONFIG_FILE),'utf8'));
  verifySdkBundle(fs.readFileSync(path.join(dir,SDK_FILE),'utf8'));
  const body=netlifyHeaders(config);
  // 'wx' creates the file or fails, so an _headers that appeared meanwhile, or a link in its place, is never written.
  fs.writeFileSync(file,body,{flag:'wx'});
  return{dir,mode:config.mode,csp:contentSecurityPolicy(config),bytes:Buffer.byteLength(body),sha256:sha256(body)};
}

if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){
  const args=process.argv.slice(2),options={};
  for(let i=0;i<args.length;i++){
    if(args[i]==='--dir'&&args[i+1])options.dir=args[++i];
    else{console.error(`Unknown argument: ${args[i]} (usage: node scripts/netlify-headers.mjs [--dir <build>])`);process.exit(2)}
  }
  try{
    const {dir,mode,csp,bytes,sha256:hash}=writeNetlifyHeaders(options);
    console.log(`Wrote ${path.join(dir,HEADERS_FILE)} for the ${mode} build`);
    console.log(`  Content-Security-Policy: ${csp}`);
    console.log(`  ${hash}  ${String(bytes).padStart(7)}  ${HEADERS_FILE}`);
  }catch(error){
    console.error(`Cannot write ${HEADERS_FILE}: ${error.message}`);
    process.exitCode=1;
  }
}
