// The browser's runtime configuration for the commercial frontend, taken from POOL_PLATFORM_* environment variables at
// build time. Only public values ever reach the browser: the mode, the Neon Auth URL, the Data API URL and a default
// pool slug. There is no variable for anything else (password, connection string, API key), so nothing else can be
// written out, and a sandbox build never names a backend.

export const ENV=Object.freeze({
  mode:'POOL_PLATFORM_MODE',
  authUrl:'POOL_PLATFORM_AUTH_URL',
  dataUrl:'POOL_PLATFORM_DATA_URL',
  defaultPoolSlug:'POOL_PLATFORM_DEFAULT_POOL_SLUG'
});
export const SANDBOX_DEFAULT_POOL_SLUG='demo-football-pool';
// The shape the database requires of tenant slugs: 3 to 64 lowercase letters, digits and inner hyphens.
const POOL_SLUG=/^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$/;
// Every character a Neon Auth or Data API URL needs. Anything else (? # @ \ % quotes, spaces, controls, non-ASCII)
// is refused, so no query string, hash fragment, embedded credential or encoded payload can get through.
const URL_CHARS=/^[A-Za-z0-9._~:/-]+$/;

export class ConfigError extends Error{
  constructor(message){super(message);this.name='ConfigError'}
}

// Error messages never repeat the value they reject: a secret pasted into the wrong variable stays out of build logs.
export function endpointUrl(variable,raw){
  if(typeof raw!=='string'||raw==='')throw new ConfigError(`${variable} is required when ${ENV.mode}=live.`);
  if(!URL_CHARS.test(raw))throw new ConfigError(`${variable} may contain only letters, digits and . _ ~ : / - (no query string, hash fragment, credentials, percent-encoding or whitespace).`);
  let url;
  try{url=new URL(raw)}catch{throw new ConfigError(`${variable} is not an absolute URL.`)}
  if(url.protocol!=='https:')throw new ConfigError(`${variable} must be an https: URL.`);
  // The URL parser silently rewrites some input (host case, default port, dot segments, a missing path); only a
  // value it leaves exactly as written is accepted, so what is configured is what the browser uses.
  if(url.href!==raw)throw new ConfigError(`${variable} must be written in canonical form: lowercase host, no default port, no dot segments, and a path.`);
  return url.href;
}

export function poolSlug(variable,raw,fallback){
  const value=raw===undefined||raw===''?fallback:raw;
  if(value==='')return '';
  if(typeof value!=='string'||!POOL_SLUG.test(value))throw new ConfigError(`${variable} must be 3 to 64 lowercase letters, digits or inner hyphens.`);
  return value;
}

export function runtimeConfigFromEnv(env={}){
  const mode=env[ENV.mode]||'sandbox';
  if(mode==='sandbox'){
    for(const variable of [ENV.authUrl,ENV.dataUrl]){
      if(env[variable])throw new ConfigError(`${variable} is set but ${ENV.mode} is not live: a sandbox build never names a backend.`);
    }
    return Object.freeze({mode,authUrl:'',dataUrl:'',defaultPoolSlug:poolSlug(ENV.defaultPoolSlug,env[ENV.defaultPoolSlug],SANDBOX_DEFAULT_POOL_SLUG)});
  }
  if(mode!=='live')throw new ConfigError(`${ENV.mode} must be sandbox or live.`);
  return Object.freeze({
    mode,
    authUrl:endpointUrl(ENV.authUrl,env[ENV.authUrl]),
    dataUrl:endpointUrl(ENV.dataUrl,env[ENV.dataUrl]),
    defaultPoolSlug:poolSlug(ENV.defaultPoolSlug,env[ENV.defaultPoolSlug],'')
  });
}

// The generated module has the same shape as the tracked platform-config.js: one frozen object literal. It is JSON
// (fixed keys, fixed order, string values only) with <, >, &, U+2028 and U+2029 escaped, so no value can end the
// string, add code, or break out of a <script> element even if the file were ever inlined. Same input, same bytes.
const UNSAFE_IN_SCRIPT=/[<>&\u2028\u2029]/g;
export function serializeRuntimeConfig(config){
  const {mode,authUrl,dataUrl,defaultPoolSlug}=config??{};
  const values={mode,authUrl,dataUrl,defaultPoolSlug};
  for(const [key,value] of Object.entries(values)){
    if(typeof value!=='string')throw new ConfigError(`runtime configuration ${key} must be a string.`);
  }
  const json=JSON.stringify(values).replace(UNSAFE_IN_SCRIPT,ch=>`\\u${ch.charCodeAt(0).toString(16).padStart(4,'0')}`);
  return `// Generated by scripts/build.mjs from ${Object.values(ENV).join(', ')}. Do not edit: rebuild instead.\nexport const PLATFORM_CONFIG=Object.freeze(${json});\n`;
}

// Reads back a platform-config.js the build wrote, without running it: the values are checked again and the file
// must be byte for byte what serializeRuntimeConfig writes for them, so a hand-edited file is refused.
export function parseRuntimeConfig(source){
  const match=/^export const PLATFORM_CONFIG=Object\.freeze\((\{[^\n]*\})\);$/m.exec(source);
  let parsed;
  try{parsed=match&&JSON.parse(match[1])}catch{parsed=null}
  if(!parsed||typeof parsed!=='object')throw new ConfigError('platform-config.js was not written by scripts/build.mjs: rebuild it.');
  const config=runtimeConfigFromEnv({
    [ENV.mode]:parsed.mode,[ENV.authUrl]:parsed.authUrl,[ENV.dataUrl]:parsed.dataUrl,[ENV.defaultPoolSlug]:parsed.defaultPoolSlug
  });
  if(serializeRuntimeConfig(config)!==source)throw new ConfigError('platform-config.js differs from what scripts/build.mjs writes for its values: rebuild it.');
  return config;
}

// The Content-Security-Policy the commercial pages are built to run under. connect-src names exactly this build's
// Auth and Data API origins (none for a sandbox), derived from its configuration, never hard-coded.
export function contentSecurityPolicy(config){
  const origins=[...new Set([config.authUrl,config.dataUrl].filter(Boolean).map(url=>new URL(url).origin))];
  return [
    "default-src 'self'","script-src 'self'","style-src 'self'","img-src 'self'","font-src 'none'",
    ["connect-src 'self'",...origins].join(' '),"worker-src 'self'","manifest-src 'self'","object-src 'none'",
    "frame-src 'none'","frame-ancestors 'none'","base-uri 'none'","form-action 'self'"
  ].join('; ');
}
