import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import http from 'node:http';
import {createRequire} from 'node:module';
import os from 'node:os';
import path from 'node:path';
import test,{describe} from 'node:test';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {PLATFORM_CONFIG} from './platform-config.js';
import {APP_DIR,OUTPUT_FILES,STATIC_FILES,buildCommercialFrontend,bundleNeonSdk,listFiles,verifySdkBundle} from './scripts/build.mjs';
import {ConfigError,contentSecurityPolicy,parseRuntimeConfig,runtimeConfigFromEnv,serializeRuntimeConfig} from './scripts/runtime-config.mjs';
import {startServer} from './scripts/serve.mjs';

// Commercial frontend readiness: the allow-listed build, the runtime configuration, the self-hosted Neon SDK, CSP
// readiness and the service-worker registration. Deterministic and offline: builds use a stub in place of the SDK
// bundle, except the block at the end, which bundles the real SDK when pool-platform's npm ci has been run.
const HERE=path.dirname(fileURLToPath(import.meta.url));
const read=name=>fs.readFileSync(path.join(HERE,name),'utf8');
const sha256=body=>crypto.createHash('sha256').update(body).digest('hex');
const ESBUILD=(()=>{try{return !!createRequire(import.meta.url).resolve('esbuild')}catch{return false}})();
const PAGES=STATIC_FILES.filter(name=>name.endsWith('.html'));
const SCRIPTS=STATIC_FILES.filter(name=>name.endsWith('.js'));
const AUTH='https://ep-example-000000.neonauth.c-0.us-east-2.aws.neon.test/neondb/auth';
const DATA='https://ep-example-000000.apirest.c-0.us-east-2.aws.neon.test/neondb/rest/v1';
const LIVE={POOL_PLATFORM_MODE:'live',POOL_PLATFORM_AUTH_URL:AUTH,POOL_PLATFORM_DATA_URL:DATA,POOL_PLATFORM_DEFAULT_POOL_SLUG:'it-pool'};
const STUB_SDK='export function createClient(){throw new Error("stub SDK")}\n';
const stubSdk=async()=>STUB_SDK;
const LS=String.fromCharCode(0x2028),PS=String.fromCharCode(0x2029),NL=String.fromCharCode(10),TAB=String.fromCharCode(9);

function scratch(t){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pool-platform-readiness-'));
  t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  return dir;
}
// The generated module as a plain script in a fresh context: what it defines, and the values it holds.
function evaluateConfig(source){
  const lines=source.split('\n').filter(Boolean);
  assert.equal(lines.length,2,'one comment line and one statement');
  assert.match(lines[0],/^\/\/ Generated by scripts\/build\.mjs/);
  assert.match(lines[1],/^export const PLATFORM_CONFIG=Object\.freeze\(\{.*\}\);$/);
  const context=vm.createContext({});
  vm.runInContext(lines[1].replace(/^export const PLATFORM_CONFIG=/,'globalThis.PLATFORM_CONFIG='),context);
  return{
    values:JSON.parse(vm.runInContext('JSON.stringify(PLATFORM_CONFIG)',context)),
    frozen:vm.runInContext('Object.isFrozen(PLATFORM_CONFIG)',context),
    globals:JSON.parse(vm.runInContext('JSON.stringify(Object.keys(globalThis).sort())',context))
  };
}

test('A: the tracked platform-config.js is a sandbox naming no backend, and no deployable source holds an absolute URL or a Neon endpoint',()=>{
  assert.deepEqual({...PLATFORM_CONFIG},{mode:'sandbox',authUrl:'',dataUrl:'',defaultPoolSlug:'demo-football-pool'});
  assert.ok(Object.isFrozen(PLATFORM_CONFIG));
  for(const name of ['platform-config.js',...STATIC_FILES]){
    const text=read(name);
    assert.doesNotMatch(text,/[a-z][a-z0-9+.-]*:\/\//i,`${name} holds an absolute URL`);
    assert.doesNotMatch(text,/neon\.tech|neonauth\.|apirest\.|\bep-[a-z]+-[a-z]+-[a-z0-9]{6,}/i,`${name} names a Neon endpoint`);
  }
  // A committed live configuration would reach GitHub Pages: keep build output and env files untracked.
  const ignored=read('.gitignore').split('\n');
  for(const pattern of ['dist/','node_modules/','.env','.env.*'])assert.ok(ignored.includes(pattern),pattern);
});

test('B: a live build without both endpoint URLs, or with a malformed one, fails closed before writing anything',async t=>{
  for(const env of [{POOL_PLATFORM_MODE:'live'},{...LIVE,POOL_PLATFORM_AUTH_URL:''},{...LIVE,POOL_PLATFORM_DATA_URL:''},
    {...LIVE,POOL_PLATFORM_AUTH_URL:undefined},{...LIVE,POOL_PLATFORM_DATA_URL:undefined}]){
    assert.throws(()=>runtimeConfigFromEnv(env),ConfigError,JSON.stringify(env));
  }
  const malformed=[
    'http://auth.example.test/neondb/auth','javascript:alert(1)','javascript:void0','javascript://auth.example.test/%0Aalert(1)',
    'data:text/javascript,alert(1)','data:x','blob:https://auth.example.test/x','file:///etc/passwd','ftp://auth.example.test/x',
    'https://user:secret@auth.example.test/neondb/auth','https://secret@auth.example.test/neondb/auth','https://:secret@auth.example.test/x',
    'https://auth.example.test/neondb/auth?apikey=secret','https://auth.example.test/neondb/auth?','https://auth.example.test/neondb/auth#secret',
    'https://auth.example.test/neondb/auth#','https://auth.example.test/%73ecret',`https://auth.example.test/x${NL}`,`${TAB}https://auth.example.test/x`,
    ' https://auth.example.test/x','https://auth.example.test/x ','https://auth.example.test/neon db/auth','https://AUTH.example.test/neondb/auth',
    'https://auth.example.test:443/neondb/auth','https://auth.example.test/neondb/../auth','https://auth.example.test/./neondb/auth',
    'https://auth.example.test','https:auth.example.test/x','https:/auth.example.test/x','//auth.example.test/x','/neondb/auth',
    'auth.example.test/neondb/auth','https://auth.example.test\\neondb\\auth','https://bücher.example.test/x',"https://auth.example.test/x'",
    'https://auth.example.test/x"','https://auth.example.test/<script>','https://auth.example.test/`x`','https://auth.example.test/${x}',
    `https://auth.example.test/x${LS}`,'https://[::1]/x','HTTPS://auth.example.test/x'
  ];
  for(const value of malformed){
    for(const variable of ['POOL_PLATFORM_AUTH_URL','POOL_PLATFORM_DATA_URL']){
      const error=(()=>{try{runtimeConfigFromEnv({...LIVE,[variable]:value})}catch(e){return e}})();
      assert.ok(error instanceof ConfigError,`${variable}=${JSON.stringify(value)} was accepted`);
      assert.match(error.message,new RegExp(variable));
      assert.doesNotMatch(error.message,/secret/,'the rejected value is never repeated');
    }
  }
  // The configuration is checked first: nothing is bundled and no output directory appears.
  const out=path.join(scratch(t),'dist');
  let bundled=false;
  await assert.rejects(buildCommercialFrontend({outDir:out,env:{POOL_PLATFORM_MODE:'live',POOL_PLATFORM_AUTH_URL:AUTH},bundleSdk:async()=>{bundled=true;return STUB_SDK}}),ConfigError);
  assert.equal(bundled,false);
  assert.equal(fs.existsSync(out),false);
});

test('C: canonical https Auth and Data API URLs are accepted and written exactly; the mode and slug are checked',()=>{
  assert.deepEqual({...runtimeConfigFromEnv(LIVE)},{mode:'live',authUrl:AUTH,dataUrl:DATA,defaultPoolSlug:'it-pool'});
  for(const url of [AUTH,DATA,'https://auth.example.test/neondb/auth','https://data.example.test/neondb/rest/v1/','https://data.example.test:8443/rest/v1','https://auth.example.test/']){
    assert.equal(runtimeConfigFromEnv({...LIVE,POOL_PLATFORM_AUTH_URL:url}).authUrl,url);
    assert.equal(runtimeConfigFromEnv({...LIVE,POOL_PLATFORM_DATA_URL:url}).dataUrl,url);
  }
  assert.equal(runtimeConfigFromEnv({...LIVE,POOL_PLATFORM_DEFAULT_POOL_SLUG:undefined}).defaultPoolSlug,'','a live build may name no default pool');
  // No configuration at all is the sandbox, which names no backend and refuses one.
  for(const env of [{},{POOL_PLATFORM_MODE:''},{POOL_PLATFORM_MODE:'sandbox'}]){
    assert.deepEqual({...runtimeConfigFromEnv(env)},{mode:'sandbox',authUrl:'',dataUrl:'',defaultPoolSlug:'demo-football-pool'});
  }
  assert.equal(runtimeConfigFromEnv({POOL_PLATFORM_DEFAULT_POOL_SLUG:'second-demo-pickem'}).defaultPoolSlug,'second-demo-pickem');
  for(const variable of ['POOL_PLATFORM_AUTH_URL','POOL_PLATFORM_DATA_URL']){
    assert.throws(()=>runtimeConfigFromEnv({[variable]:AUTH}),/is set but POOL_PLATFORM_MODE is not live/);
  }
  for(const mode of ['LIVE','Live',' live','production','true','1'])assert.throws(()=>runtimeConfigFromEnv({...LIVE,POOL_PLATFORM_MODE:mode}),ConfigError,mode);
  for(const slug of ['Demo','ab','-demo','demo-','demo_pool','demo/pool','../demo','demo pool',"demo'",'a'.repeat(65),`demo${NL}`]){
    assert.throws(()=>runtimeConfigFromEnv({...LIVE,POOL_PLATFORM_DEFAULT_POOL_SLUG:slug}),ConfigError,slug);
  }
  assert.equal(runtimeConfigFromEnv({...LIVE,POOL_PLATFORM_DEFAULT_POOL_SLUG:'a'.repeat(64)}).defaultPoolSlug,'a'.repeat(64));
});

test('D: the generated configuration is inert data: hostile values stay strings, nothing else is defined, same input same bytes',()=>{
  const hostile=["'",'"','`','${globalThis.pwned=1}','</script><script>globalThis.pwned=1</script>','\\','*/globalThis.pwned=1;/*',
    `${LS}globalThis.pwned=1${PS}`,`${NL}globalThis.pwned=1`,'"});globalThis.pwned=1;({"',"');globalThis.pwned=1;('",'<!--','-->','&amp;<>'];
  const unsafe=new RegExp(`[<>&${LS}${PS}]`);
  for(const value of hostile){
    const config={mode:value,authUrl:value,dataUrl:value,defaultPoolSlug:value};
    const source=serializeRuntimeConfig(config);
    assert.doesNotMatch(source.split('\n')[1],unsafe,JSON.stringify(value));
    const {values,frozen,globals}=evaluateConfig(source);
    assert.deepEqual(values,config,JSON.stringify(value));
    assert.equal(frozen,true);
    assert.deepEqual(globals,['PLATFORM_CONFIG'],'nothing but PLATFORM_CONFIG is defined');
    assert.equal(serializeRuntimeConfig({...config}),source,'same input, same bytes');
  }
  // Only the four keys, in a fixed order, and only strings.
  const extra=serializeRuntimeConfig({defaultPoolSlug:'d',dataUrl:'',authUrl:'',mode:'sandbox',password:'secret',toString:'x'});
  assert.match(extra,/Object\.freeze\(\{"mode":"sandbox","authUrl":"","dataUrl":"","defaultPoolSlug":"d"\}\);/);
  for(const bad of [null,1,true,{},[],undefined]){
    assert.throws(()=>serializeRuntimeConfig({mode:'sandbox',authUrl:bad,dataUrl:'',defaultPoolSlug:'d'}),ConfigError);
  }
  // A build's own output reads back exactly; a file the build could not have written is refused rather than trusted:
  // extra code, another shape, a value no build accepts (a sandbox that names a backend, an http: URL).
  for(const env of [{},LIVE]){
    const config=runtimeConfigFromEnv(env),source=serializeRuntimeConfig(config);
    assert.deepEqual({...parseRuntimeConfig(source)},{...config});
    assert.deepEqual(evaluateConfig(source).values,{...config});
    for(const edited of [`${source}globalThis.pwned=1;\n`,source.replace('Object.freeze(','('),source.replace('\n',' '),source.replace(/"mode":"\w+"/,'"mode":"sandbox"').replace(/"authUrl":""/,'"authUrl":"https://auth.example.test/x"'),
      source.replace(/"authUrl":"[^"]*"/,'"authUrl":"http://auth.example.test/x"').replace(/"mode":"\w+"/,'"mode":"live"'),read('platform-config.js')]){
      assert.notEqual(edited,source);
      assert.throws(()=>parseRuntimeConfig(edited),ConfigError,edited);
    }
  }
  // Values are read, not assumed: another build's well-formed output reads as that build's values.
  const other=serializeRuntimeConfig(runtimeConfigFromEnv({...LIVE,POOL_PLATFORM_AUTH_URL:'https://auth.example.test/neondb/auth'}));
  assert.equal(parseRuntimeConfig(other).authUrl,'https://auth.example.test/neondb/auth');
});

test('E: PlatformClient imports the SDK from the same-origin vendor module; no deployable script imports from a CDN or another origin',()=>{
  const client=read('platform-client.js');
  assert.doesNotMatch(client,/jsdelivr|unpkg|esm\.sh|skypack|jspm|https?:/i);
  assert.deepEqual([...client.matchAll(/\bimport\s*\(([^)]*)\)/g)].map(m=>m[1]),["'./vendor/neon-js.js'"]);
  for(const name of SCRIPTS){
    const js=read(name);
    const specifiers=[...js.matchAll(/^import\s+(?:[^'"\n]*\s+from\s+)?(['"])([^'"]+)\1;$/gm),...js.matchAll(/\bimport\(\s*(['"])([^'"]+)\1\s*\)/g)].map(m=>m[2]);
    assert.equal(specifiers.length,(js.match(/^import\b/gm)||[]).length+(js.match(/\bimport\(/g)||[]).length,`${name}: every import has a literal specifier`);
    for(const specifier of specifiers)assert.match(specifier,/^\.\/[a-z][a-z0-9-]*(?:\/[a-z][a-z0-9-]*)?\.js$/,`${name} imports ${specifier}`);
  }
});

test('E: the build refuses an SDK bundle that imports anything, names a CDN, carries another version or lacks createClient',()=>{
  const record='\nvar name3 = "@neondatabase/neon-js";\nvar version6 = "0.7.0-beta";\nfunction buildNeonJsClientInfo() {\n  const info = getClientInfo2(name3, version6);\n';
  const good=`// bundle${record}  return info;\n}\nexport {\n  createClient,\n  fetchWithToken\n};\n`;
  assert.equal(verifySdkBundle(good),good);
  for(const [bad,reason] of [
    [`import {x} from "y";\n${good}`,/not self-contained/],[`import "y";\n${good}`,/not self-contained/],[`import * as y from "y";\n${good}`,/not self-contained/],
    [`${good}const later=()=>import("./chunk.js");\n`,/not self-contained/],[`${good}// https://cdn.jsdelivr.net/npm/x\n`,/names a CDN/],
    [good.replace('0.7.0-beta','0.7.1-beta'),/version record/],[good.replace('@neondatabase/neon-js','@neondatabase/other'),/version record/],
    [good.replace('  createClient,\n',''),/does not export createClient/]
  ])assert.throws(()=>verifySdkBundle(bad),reason);
});

test('F: @neondatabase/neon-js is pinned to exactly 0.7.0-beta and esbuild to an exact version; the package is private',()=>{
  const pkg=JSON.parse(read('package.json'));
  assert.equal(pkg.private,true);
  assert.deepEqual(pkg.dependencies,{'@neondatabase/neon-js':'0.7.0-beta'});
  assert.deepEqual(Object.keys(pkg.devDependencies),['esbuild']);
  for(const version of [...Object.values(pkg.dependencies),...Object.values(pkg.devDependencies)]){
    assert.match(version,/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?$/,`${version} is not an exact version`);
  }
});

test('G: package-lock.json pins the exact SDK tarball and integrity, locks every package, and matches the SDK tree the live harness validated',()=>{
  const lock=JSON.parse(read('package-lock.json')),packages=lock.packages;
  assert.equal(lock.lockfileVersion,3);
  assert.deepEqual(packages[''].dependencies,{'@neondatabase/neon-js':'0.7.0-beta'});
  const sdk=packages['node_modules/@neondatabase/neon-js'];
  assert.equal(sdk.version,'0.7.0-beta');
  assert.equal(sdk.resolved,'https://registry.npmjs.org/@neondatabase/neon-js/-/neon-js-0.7.0-beta.tgz');
  assert.equal(sdk.integrity,'sha512-TZiMKvYU90/P5E1aXDPW0eY1wQmV4KWHjlYQ4zqnvGsXhaklHuXUsEZ9FiaaF343wxzMBTe2b+RtJ5Q8yCHMjQ==');
  for(const [key,entry] of Object.entries(packages)){
    if(!key)continue;
    assert.match(entry.version,/^\d+\.\d+\.\d+/,key);
    assert.match(entry.resolved,/^https:\/\/registry\.npmjs\.org\//,key);
    assert.match(entry.integrity,/^sha512-/,key);
  }
  // The tree the browser bundle is made from is, package for package, the one the live harness ran against Neon.
  const harness=JSON.parse(read('validation/live/package-lock.json')).packages;
  const shared=Object.keys(packages).filter(key=>key&&harness[key]);
  for(const key of shared){
    assert.deepEqual([packages[key].version,packages[key].resolved,packages[key].integrity],[harness[key].version,harness[key].resolved,harness[key].integrity],key);
  }
  assert.ok(shared.length>=200,`${shared.length} shared packages`);
  const ours=Object.keys(packages).filter(key=>key&&!harness[key]);
  assert.ok(ours.every(key=>/^node_modules\/(?:esbuild|@esbuild\/[a-z0-9-]+)$/.test(key)),`only the bundler is ours alone: ${ours.join(' ')}`);
});

test('H: a build writes exactly the allow-listed files, byte for byte, plus the generated configuration and SDK, and nothing the pages need is missing',async t=>{
  const out=path.join(scratch(t),'dist');
  const result=await buildCommercialFrontend({outDir:out,env:{},bundleSdk:stubSdk});
  assert.deepEqual(listFiles(out),OUTPUT_FILES);
  assert.deepEqual(OUTPUT_FILES,[...STATIC_FILES,'platform-config.js','vendor/neon-js.js'].sort());
  for(const name of STATIC_FILES)assert.ok(fs.readFileSync(path.join(out,name)).equals(fs.readFileSync(path.join(HERE,name))),name);
  assert.equal(fs.readFileSync(path.join(out,'platform-config.js'),'utf8'),serializeRuntimeConfig(runtimeConfigFromEnv({})));
  assert.equal(fs.readFileSync(path.join(out,'vendor/neon-js.js'),'utf8'),STUB_SDK);
  assert.deepEqual(result.files.map(f=>f.name),OUTPUT_FILES);
  for(const file of result.files)assert.equal(file.sha256,sha256(fs.readFileSync(path.join(out,file.name))),file.name);
  assert.equal(result.csp,contentSecurityPolicy(result.config));
  // Everything a page, a script or the worker asks for is in the output; every allow-listed file is asked for.
  const wanted=new Set(['index.html']);
  for(const page of PAGES)for(const m of read(page).matchAll(/\b(?:src|href)="\.\/([^"]*)"/g))wanted.add(m[1]||'index.html');
  for(const name of SCRIPTS)for(const m of read(name).matchAll(/(?:\bfrom\s*|\bimport\s*\(?\s*)'\.\/([^']+)'/g))wanted.add(m[1]);
  for(const m of read('service-worker.js').matchAll(/'\.\/([^']*)'/g))wanted.add(m[1]||'index.html');
  wanted.add('service-worker.js');
  assert.deepEqual([...wanted].sort(),OUTPUT_FILES);
});

test('I: nothing beside the allow-list is copied (private Pool Center files, secrets, a planted config, other apps), and output directories are guarded',async t=>{
  const root=scratch(t),app=path.join(root,'pool-platform');
  const plant=(file,body)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,body)};
  for(const name of STATIC_FILES)plant(path.join(app,name),fs.readFileSync(path.join(HERE,name)));
  const DECOY='DECOY-9f2c41';
  for(const name of ['.env','.env.local','secrets.json','nfl-pool.html','private.js','docs/NOTES.md','migrations/999_x.sql','validation/live/secrets.json',
    'node_modules/x/index.js','scripts/build.mjs','vendor/other.js','package.json','README.md','ui-contract.test.mjs']){
    plant(path.join(app,name),`${DECOY} ${name}`);
  }
  plant(path.join(app,'platform-config.js'),`export const PLATFORM_CONFIG=Object.freeze({mode:'live',authUrl:'https://${DECOY}.example.test/a',dataUrl:'https://${DECOY}.example.test/d'});`);
  plant(path.join(root,'nfl-pool','index.html'),`${DECOY} private Pool Center`);
  plant(path.join(root,'index.html'),`${DECOY} repository root`);
  const out=path.join(root,'out');
  await buildCommercialFrontend({appDir:app,outDir:out,env:{},bundleSdk:stubSdk});
  assert.deepEqual(listFiles(out),OUTPUT_FILES);
  for(const file of listFiles(out))assert.ok(!fs.readFileSync(path.join(out,file),'utf8').includes(DECOY),file);
  assert.equal(parseRuntimeConfig(fs.readFileSync(path.join(out,'platform-config.js'),'utf8')).mode,'sandbox','the planted config is never copied');
  // Rebuilding replaces a previous build; a symbolic link in place of an allow-listed file is refused.
  await buildCommercialFrontend({appDir:app,outDir:out,env:LIVE,bundleSdk:stubSdk});
  assert.deepEqual(listFiles(out),OUTPUT_FILES);
  fs.rmSync(path.join(app,'styles.css'));fs.symlinkSync(path.join(root,'nfl-pool','index.html'),path.join(app,'styles.css'));
  await assert.rejects(buildCommercialFrontend({appDir:app,outDir:out,env:{},bundleSdk:stubSdk}),/styles\.css must be a regular file/);
  fs.rmSync(path.join(app,'styles.css'));fs.copyFileSync(path.join(HERE,'styles.css'),path.join(app,'styles.css'));
  // Never into the sources or a directory holding them, never elsewhere inside the app than dist/, never over foreign files.
  for(const [outDir,reason] of [[root,/contains the application sources/],[app,/contains the application sources/],[path.join(app,'docs'),/only dist\/ may be written/],[path.join(app,'dist','x'),/only dist\/ may be written/]]){
    await assert.rejects(buildCommercialFrontend({appDir:app,outDir,env:{},bundleSdk:stubSdk}),reason,outDir);
  }
  const foreign=path.join(root,'foreign');plant(path.join(foreign,'keep.txt'),'keep');
  await assert.rejects(buildCommercialFrontend({appDir:app,outDir:foreign,env:{},bundleSdk:stubSdk}),/holds keep\.txt/);
  plant(path.join(app,'dist','stale.js'),'stale');
  await assert.rejects(buildCommercialFrontend({appDir:app,env:{},bundleSdk:stubSdk}),/holds stale\.js/);
  assert.ok(fs.existsSync(path.join(foreign,'keep.txt'))&&fs.existsSync(path.join(app,'dist','stale.js')),'nothing was deleted');
  fs.rmSync(path.join(app,'dist'),{recursive:true});
  await buildCommercialFrontend({appDir:app,env:{},bundleSdk:stubSdk});
  assert.deepEqual(listFiles(path.join(app,'dist')),OUTPUT_FILES,'dist/ inside the app is the default output');
  // In the real tree every allow-listed file is a regular file directly in pool-platform/.
  for(const name of STATIC_FILES){
    assert.equal(path.dirname(path.join(APP_DIR,name)),APP_DIR,name);
    assert.ok(fs.lstatSync(path.join(APP_DIR,name)).isFile(),name);
  }
});

test('J: commercial pages hold no inline script, event-handler attribute or javascript: URL; every script is an external same-origin module',()=>{
  assert.deepEqual(PAGES,['index.html','participant.html','commissioner.html']);
  for(const name of PAGES){
    const html=read(name),scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi)];
    assert.ok(scripts.length>=1,name);
    assert.equal((html.match(/<script\b/gi)||[]).length,scripts.length,name);
    for(const [,attributes,body] of scripts){
      assert.equal(body.trim(),'',`${name}: inline script`);
      assert.match(attributes,/^ type="module" src="\.\/[a-z][a-z0-9-]*\.js"$/,`${name}: ${attributes}`);
    }
    assert.doesNotMatch(html,/\son[a-z]+\s*=/i,`${name}: event-handler attribute`);
    assert.doesNotMatch(html,/javascript:|<iframe|<object|<embed|<base\b|http-equiv/i,name);
  }
  assert.match(read('index.html'),/<script type="module" src="\.\/sw-register\.js"><\/script>/);
  // Nor does any script build markup that carries a handler, or run strings as code.
  for(const name of SCRIPTS){
    const js=read(name);
    assert.doesNotMatch(js,/\son[a-z]+\s*=\s*["'\\]|<script/i,`${name}: markup with a handler or script`);
    assert.doesNotMatch(js,/\beval\s*\(|\bnew Function\b|\bFunction\s*\(|set(?:Timeout|Interval)\(\s*['"`]|document\.write/,name);
  }
});

test('K: commercial pages carry no style attribute or <style> element, no script styles through markup, and the classes that replaced them keep the same rules',()=>{
  for(const name of PAGES){
    assert.doesNotMatch(read(name),/\sstyle\s*=/i,name);
    assert.doesNotMatch(read(name),/<style\b/i,name);
  }
  for(const name of SCRIPTS)assert.doesNotMatch(read(name),/\bstyle\s*=|\.style\b|cssText|setAttribute\(\s*['"]style/,name);
  const css=read('styles.css');
  assert.match(css,/\.action-bar\{margin-top:14px\}/,'index.html: was style="margin-top:14px"');
  assert.match(read('index.html'),/<div class="actions action-bar">/);
  assert.match(css,/\.compact\{min-height:42px;[^}]*\}\.tap-target\{min-height:44px\}/,'Sign out: was style="min-height:44px"');
  assert.match(css,/\.shell-notice\{margin-bottom:14px\}/,'sessionError: was style="margin-bottom:14px"');
  for(const page of ['participant.html','commissioner.html']){
    assert.match(read(page),/<button class="button compact secondary hidden tap-target" id="signOut" type="button">/,page);
    assert.match(read(page),/<div class="notice error hidden shell-notice" id="sessionError" role="alert">/,page);
  }
  // Nothing in the stylesheet needs img-src, font-src or another origin.
  assert.doesNotMatch(css,/@import|url\(|@font-face|image-set\(/i);
});

test('L: the service worker is registered in one place, for the commercial directory only, from every page',()=>{
  const calls=[];
  vm.runInNewContext(read('sw-register.js'),{navigator:{serviceWorker:{register:(url,options)=>{calls.push(JSON.parse(JSON.stringify([url,options])));return Promise.resolve()}}}});
  assert.deepEqual(calls,[['./service-worker.js',{scope:'./',updateViaCache:'none'}]]);
  vm.runInNewContext(read('sw-register.js'),{navigator:{}});
  for(const name of STATIC_FILES.filter(n=>n!=='sw-register.js'))assert.doesNotMatch(read(name),/serviceWorker\s*\.\s*register\s*\(/,name);
  for(const name of ['participant.js','commissioner.js'])assert.match(read(name),/^import '\.\/sw-register\.js';$/m,name);
  assert.match(read('service-worker.js'),/const STATIC_PATHS=new Set\(ASSETS\.map\(asset=>new URL\(asset,self\.location\)\.pathname\)\);/);
  // Scope './' resolves against the page, and every page sits beside the worker, as the manifest's scope does.
  for(const page of PAGES)assert.equal(path.posix.dirname(page),'.');
  assert.equal(JSON.parse(read('manifest.webmanifest')).scope,'./');
});

test('R: a sandbox and a live build differ only in platform-config.js, and a sandbox build needs no live configuration',async t=>{
  const dir=scratch(t),sandbox=path.join(dir,'sandbox'),live=path.join(dir,'live');
  await buildCommercialFrontend({outDir:sandbox,env:{},bundleSdk:stubSdk});
  await buildCommercialFrontend({outDir:live,env:LIVE,bundleSdk:stubSdk});
  const differing=OUTPUT_FILES.filter(name=>!fs.readFileSync(path.join(sandbox,name)).equals(fs.readFileSync(path.join(live,name))));
  assert.deepEqual(differing,['platform-config.js']);
  assert.equal(evaluateConfig(fs.readFileSync(path.join(sandbox,'platform-config.js'),'utf8')).values.mode,'sandbox');
  assert.deepEqual(evaluateConfig(fs.readFileSync(path.join(live,'platform-config.js'),'utf8')).values,{mode:'live',authUrl:AUTH,dataUrl:DATA,defaultPoolSlug:'it-pool'});
  // Sandbox pages never load the SDK: PlatformClient.init() returns before its import unless the mode is live.
  assert.match(read('platform-client.js'),/async init\(\)\{\n    if\(!this\.live\)return this;\n[^\n]*\n    const \{createClient\}=await import\('\.\/vendor\/neon-js\.js'\);/);
});

test('S: each page reads platform-config.js from the network as it loads and, without it, fails closed: a message and no sandbox fallback',()=>{
  for(const [name,say] of [['participant.js','message'],['commissioner.js','msg']]){
    const js=read(name);
    assert.doesNotMatch(js,/^import[^\n]*platform-config/m,`${name}: a static import would fail the whole page silently`);
    assert.match(js,new RegExp(`\\nconst \\{PLATFORM_CONFIG\\}=await import\\('\\./platform-config\\.js'\\)\\.catch\\(e=>\\{\\$\\('modePill'\\)\\.textContent='UNAVAILABLE';${say}\\('sessionError',CONFIG_UNAVAILABLE\\);throw e\\}\\);\\n`),name);
    assert.equal(js.match(/\bPLATFORM_CONFIG\b/g).length,3,`${name}: loaded once, then read only for the pool slug and the client`);
  }
});

// The local server behind the localhost browser checks.
function get(port,pathname,{host=`localhost:${port}`,method='GET',address='127.0.0.1'}={}){
  return new Promise((resolve,reject)=>{
    const request=http.request({host:address,port,path:pathname,method,headers:{host}},response=>{
      const chunks=[];response.on('data',c=>chunks.push(c));response.on('end',()=>resolve({status:response.statusCode,headers:response.headers,body:Buffer.concat(chunks).toString('utf8')}));
    });
    request.on('error',reject);request.end();
  });
}

test('the local server answers only http://localhost:<port>, only built files, with the build\'s CSP, no Service-Worker-Allowed, and logs no query string',async t=>{
  const dir=scratch(t),dist=path.join(dir,'dist');
  await buildCommercialFrontend({outDir:dist,env:{},bundleSdk:stubSdk});
  const lines=[],server=await startServer({dir:dist,port:0,log:line=>lines.push(line)});
  t.after(()=>server.close());
  const {port}=server;
  assert.equal(server.url,`http://localhost:${port}/`);
  assert.equal(server.csp,contentSecurityPolicy(runtimeConfigFromEnv({})));
  assert.match(server.csp,/connect-src 'self';/);
  const home=await get(port,'/');
  assert.equal(home.status,200);
  assert.equal(home.body,read('index.html'));
  assert.equal(home.headers['content-type'],'text/html; charset=utf-8');
  assert.equal(home.headers['content-security-policy'],server.csp);
  assert.equal(home.headers['x-content-type-options'],'nosniff');
  assert.equal(home.headers['cache-control'],'no-cache');
  assert.equal(home.headers['service-worker-allowed'],undefined);
  for(const [pathname,type] of [['/platform-config.js','text/javascript; charset=utf-8'],['/vendor/neon-js.js','text/javascript; charset=utf-8'],['/styles.css','text/css; charset=utf-8'],['/manifest.webmanifest','application/manifest+json; charset=utf-8'],['/service-worker.js','text/javascript; charset=utf-8']]){
    const response=await get(port,pathname);
    assert.deepEqual([response.status,response.headers['content-type']],[200,type],pathname);
    assert.equal(response.headers['service-worker-allowed'],undefined,pathname);
  }
  assert.equal((await get(port,'/platform-config.js')).body,serializeRuntimeConfig(runtimeConfigFromEnv({})));
  const invite='ab'.repeat(32);
  assert.equal((await get(port,`/participant.html?pool=demo&invite=${invite}`)).status,200);
  assert.ok(lines.includes('GET /participant.html 200'));
  assert.ok(lines.every(line=>!line.includes('?')&&!line.includes(invite)),'no query string or invite token is logged');
  // Any Host but localhost:<port> is refused, 127.0.0.1 included, naming the origin to use instead.
  for(const host of [`127.0.0.1:${port}`,`[::1]:${port}`,'localhost',`LOCALHOST:${port}`,`localhost:${port+1}`,'evil.example.test']){
    const refused=await get(port,'/',{host});
    assert.equal(refused.status,421,host);
    assert.match(refused.body,new RegExp(`Open http://localhost:${port}/ instead`));
  }
  assert.equal((await get(port,'/',{method:'POST'})).status,405);
  assert.equal((await get(port,'/',{method:'HEAD'})).body,'');
  // Only files the build wrote, never a path outside it, a directory, or an unknown type.
  fs.writeFileSync(path.join(dir,'secret.js'),'secret');
  fs.symlinkSync(path.join(dir,'secret.js'),path.join(dist,'linked.js'));
  for(const pathname of ['/../secret.js','/%2e%2e/secret.js','/..%2fsecret.js','/vendor/../../secret.js','/linked.js','/vendor/','/vendor','//index.html',
    '/index.html/','/%00','/.env','/package.json','/scripts/build.mjs','/dist/index.html','/index.html%00.js','/\\..\\secret.js']){
    assert.equal((await get(port,pathname)).status,404,pathname);
  }
  // Both loopback families answer, so "localhost" works whichever a browser, curl or adb reverse tries first.
  const v6=await get(port,'/',{address:'::1'}).catch(()=>null);
  if(v6)assert.equal(v6.status,200);
});

test('the local server derives connect-src from the built configuration and refuses a directory that is not a build',async t=>{
  const dir=scratch(t),dist=path.join(dir,'dist');
  await buildCommercialFrontend({outDir:dist,env:LIVE,bundleSdk:stubSdk});
  const server=await startServer({dir:dist,port:0,log:()=>{}});
  t.after(()=>server.close());
  assert.equal(server.config.mode,'live');
  assert.match(server.csp,/connect-src 'self' https:\/\/ep-example-000000\.neonauth\.c-0\.us-east-2\.aws\.neon\.test https:\/\/ep-example-000000\.apirest\.c-0\.us-east-2\.aws\.neon\.test;/);
  for(const directive of ["default-src 'self'","script-src 'self'","style-src 'self'","img-src 'self'","font-src 'none'","worker-src 'self'","manifest-src 'self'","object-src 'none'","frame-src 'none'","frame-ancestors 'none'","base-uri 'none'","form-action 'self'"]){
    assert.ok(server.csp.split('; ').includes(directive),directive);
  }
  assert.doesNotMatch(server.csp,/unsafe-inline|unsafe-eval|\*|data:|https:(?!\/\/)/);
  fs.appendFileSync(path.join(dist,'platform-config.js'),'globalThis.pwned=1;\n');
  await assert.rejects(startServer({dir:dist,port:0,log:()=>{}}),/not a commercial build/);
  await assert.rejects(startServer({dir:path.join(dir,'missing'),port:0,log:()=>{}}),/run npm run build first/);
});

describe('the real Neon SDK bundle',{skip:ESBUILD?false:'run npm ci in pool-platform to bundle the real SDK'},()=>{
  test('is exactly @neondatabase/neon-js 0.7.0-beta from the lockfile, in one self-contained module with the package\'s own exports',async()=>{
    const code=await bundleNeonSdk();
    assert.match(code.split('\n')[0],/^\/\/ @neondatabase\/neon-js 0\.7\.0-beta, the exact package from package-lock\.json, bundled by scripts\/build\.mjs with esbuild 0\.28\.2\. Do not edit\.$/);
    assert.doesNotMatch(code,/^\s*import\s*[\w{*'"]/m);
    assert.doesNotMatch(code,/\bimport\s*\(|cdn\.jsdelivr\.net|unpkg\.com|esm\.sh/);
    assert.match(code,/\nvar name\d* = "@neondatabase\/neon-js";\nvar version\d* = "0\.7\.0-beta";\n/);
    const bundled=await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
    const original=await import('@neondatabase/neon-js');
    assert.deepEqual(Object.keys(bundled).sort(),Object.keys(original).sort());
    assert.equal(typeof bundled.createClient,'function');
    // Eval-like code: only zod's two sites. The probe catches the CSP refusal and zod then never calls compile().
    assert.doesNotMatch(code,/\beval\s*\(|\bnew Function\b/);
    assert.equal(code.match(/\bconst F = Function;/g).length,2);
    assert.match(code,/var allowsEval\d* = cached\d*\(\(\) => \{\n[^\n]*\n[^\n]*\n  \}\n  try \{\n    const F = Function;\n    new F\(""\);\n    return true;\n  \} catch \(_\) \{\n    return false;\n  \}\n\}\);/);
    assert.match(code,/\n  compile\(\) \{\n    const F = Function;\n/);
    assert.match(code,/const fastEnabled = jit && allowsEval\d*\.value;/);
    // What reaches the browser: no React (the unused adapter chain is dropped) and no Node-only package or built-in.
    // Every process access left is behind a typeof process check; the Chromium run shows none of them throws.
    assert.doesNotMatch(code,/useSyncExternalStore|react\.production|BetterAuthReactAdapterImpl|pg-native|pg-cloudflare|prettier|\bmeow\b/);
    assert.doesNotMatch(code,/\brequire\(\s*["'](?:node:)?(?:fs|path|os|net|tls|dns|crypto|child_process|http|https|stream|zlib|util)["']\s*\)|from\s*["']node:/);
  });

  test('a real build is reproducible, and sandbox and live builds differ only in platform-config.js',async t=>{
    const dir=scratch(t);
    const results=[];
    for(const [name,env] of [['one',{}],['two',{}],['live',LIVE]]){
      results.push(await buildCommercialFrontend({outDir:path.join(dir,name),env}));
    }
    const hashes=result=>Object.fromEntries(result.files.map(f=>[f.name,f.sha256]));
    assert.deepEqual(hashes(results[0]),hashes(results[1]),'same inputs, same bytes');
    const differing=OUTPUT_FILES.filter(name=>hashes(results[0])[name]!==hashes(results[2])[name]);
    assert.deepEqual(differing,['platform-config.js']);
    assert.ok(results[0].files.find(f=>f.name==='vendor/neon-js.js').bytes>100000);
  });
});
