import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import os from 'node:os';
import path from 'node:path';
import test,{describe} from 'node:test';
import {fileURLToPath} from 'node:url';
import {APP_DIR,OUTPUT_FILES,STATIC_FILES,buildCommercialFrontend,listFiles} from './scripts/build.mjs';
import {HEADERS_FILE,netlifyHeaders,writeNetlifyHeaders} from './scripts/netlify-headers.mjs';
import {ConfigError,contentSecurityPolicy,parseRuntimeConfig,runtimeConfigFromEnv} from './scripts/runtime-config.mjs';
import {startServer} from './scripts/serve.mjs';

// The Netlify build settings (netlify.toml, .nvmrc) and the generated dist/_headers. Deterministic and offline: builds
// use a stand-in for the SDK bundle that has the bundle's checked shape, except the last block, which bundles the real
// SDK when pool-platform's npm ci has been run. Netlify itself is never contacted; what only a real deploy can show is
// listed for the hosting spike in docs/HOSTING_ARCHITECTURE.md.
const HERE=path.dirname(fileURLToPath(import.meta.url));
const read=name=>fs.readFileSync(path.join(HERE,name),'utf8');
const sha256=body=>crypto.createHash('sha256').update(body).digest('hex');
const ESBUILD=(()=>{try{return !!createRequire(import.meta.url).resolve('esbuild')}catch{return false}})();
const TARGET_BRANCH='commercial-v1-netlify-adapter';
const AUTH='https://ep-example-000000.neonauth.c-0.us-east-2.aws.neon.tech/neondb/auth';
const DATA='https://ep-example-000000.apirest.c-0.us-east-2.aws.neon.test/neondb/rest/v1';
const LIVE={POOL_PLATFORM_MODE:'live',POOL_PLATFORM_DATA_URL:DATA,POOL_PLATFORM_DEFAULT_POOL_SLUG:'it-pool'};
const PROXY={POOL_PLATFORM_MODE:'live',POOL_PLATFORM_AUTH_UPSTREAM_URL:AUTH};
// The SDK bundle's checked shape (verifySdkBundle): its own name/version record and createClient exported.
const SDK_STAND_IN='// stand-in for the bundled SDK\nvar name3 = "@neondatabase/neon-js";\nvar version6 = "0.7.0-beta";\nfunction buildNeonJsClientInfo() {\n  const info = getClientInfo2(name3, version6);\n  return info;\n}\nexport {\n  createClient\n};\n';
const LIVE_CSP="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; font-src 'none'; connect-src 'self' https://ep-example-000000.apirest.c-0.us-east-2.aws.neon.test; worker-src 'self'; manifest-src 'self'; object-src 'none'; frame-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'";
const SANDBOX_CSP="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; font-src 'none'; connect-src 'self'; worker-src 'self'; manifest-src 'self'; object-src 'none'; frame-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'";
const expectedHeaders=(mode,csp)=>[
  `# Generated by scripts/netlify-headers.mjs from the ${mode} build's platform-config.js. Do not edit: rebuild instead.`,
  '/*',
  `  Content-Security-Policy: ${csp}`,
  '  X-Content-Type-Options: nosniff',
  '  Referrer-Policy: no-referrer',
  '  Cache-Control: no-cache',
  '  Strict-Transport-Security: max-age=31536000',
  ''
].join('\n');

function scratch(t){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pool-platform-netlify-'));
  t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  return dir;
}
async function built(t,env={},bundle=SDK_STAND_IN){
  const dir=path.join(scratch(t),'dist');
  await buildCommercialFrontend({outDir:dir,env,bundleSdk:async()=>bundle});
  return dir;
}
// Refused, and nothing written: no _headers appears (or an existing one keeps its bytes).
function refused(dir,reason,label){
  const before=fs.existsSync(path.join(dir,HEADERS_FILE))?fs.readFileSync(path.join(dir,HEADERS_FILE)):null;
  assert.throws(()=>writeNetlifyHeaders({dir}),reason,label);
  const after=fs.existsSync(path.join(dir,HEADERS_FILE))?fs.readFileSync(path.join(dir,HEADERS_FILE)):null;
  assert.deepEqual(after,before,`${label}: nothing written`);
}

// A strict reader for the small TOML subset netlify.toml may use: comments, blank lines, [table] headers, and
// key = "string" | 'string' | true | false. Anything else (an array of tables such as [[headers]] or [[redirects]],
// an inline table, an array, a trailing comment, an escape) is refused, so the file cannot grow a setting unseen.
function parseNetlifyToml(text){
  const tables={};
  let table=null;
  for(const [index,raw] of text.split('\n').entries()){
    const line=raw.trim();
    if(line===''||line.startsWith('#'))continue;
    const header=/^\[([a-z]+(?:\.[a-z]+)*)\]$/.exec(line);
    if(header){
      assert.ok(!Object.hasOwn(tables,header[1]),`[${header[1]}] twice`);
      table=tables[header[1]]={};
      continue;
    }
    const pair=/^([a-z_]+) = (?:"([^"\\]*)"|'([^'\\]*)'|(true|false))$/.exec(line);
    assert.ok(pair&&table,`netlify.toml line ${index+1} is not a plain key = value inside a table: ${raw}`);
    const [,key,basic,literal,flag]=pair;
    assert.ok(!Object.hasOwn(table,key),`${key} twice`);
    table[key]=basic??literal??flag==='true';
  }
  return tables;
}
const TOML=parseNetlifyToml(read('netlify.toml'));
// The generator's code without its full-line comments, for checks on what it does rather than what it says.
const GENERATOR_CODE=read('scripts/netlify-headers.mjs').split('\n').filter(line=>!line.trim().startsWith('//')).join('\n');

// Runs a netlify.toml command as Netlify does (Bash, from a base directory) with only the given build metadata, and
// with rm, npm and node replaced by stubs that record their arguments, so nothing is deleted, installed or built.
// PATH holds the stubs alone and is set last, so no test's environment can put a real tool in reach. The base
// directory is a scratch stand-in, never pool-platform/, holding a dist/ with a sentinel file that must survive every
// run: whatever a command runs, the developer's tree is never its target, and the rm stub deletes nothing.
const BASH=spawnSync('bash',['-c','command -v bash'],{encoding:'utf8'}).stdout.trim();
function runCommand(t,command,env,{fail}={}){
  const root=scratch(t),bin=path.join(root,'bin'),base=path.join(root,'base'),log=path.join(bin,'calls.log');
  const sentinel=path.join(base,'dist','sentinel');
  fs.mkdirSync(bin);
  fs.mkdirSync(path.dirname(sentinel),{recursive:true});
  fs.writeFileSync(sentinel,'');
  for(const tool of ['rm','npm','node']){
    fs.writeFileSync(path.join(bin,tool),`#!/bin/sh\nprintf '%s\\n' "${tool} $*" >> "$STUB_LOG"\nif [ "${tool} $1" = "$STUB_FAIL" ]; then exit 7; fi\nexit 0\n`,{mode:0o755});
  }
  const run=spawnSync(BASH,['-c',command],{cwd:base,encoding:'utf8',env:{STUB_LOG:log,...(fail?{STUB_FAIL:fail}:{}),...env,PATH:bin}});
  assert.ok(fs.existsSync(sentinel),'the rm stub deleted nothing');
  return{status:run.status,stderr:run.stderr,calls:fs.existsSync(log)?fs.readFileSync(log,'utf8').split('\n').filter(Boolean):[]};
}
const ALLOWED={CONTEXT:'production',BRANCH:TARGET_BRANCH};
const REFUSED=[
  {CONTEXT:'production',BRANCH:'main'},{CONTEXT:'production',BRANCH:'commercial-v1-f1-auth-proxy-corrective-3'},{CONTEXT:'production',BRANCH:`${TARGET_BRANCH}-2`},
  {CONTEXT:'production',BRANCH:`${TARGET_BRANCH} `},{CONTEXT:'production',BRANCH:'Commercial-v1-netlify-adapter'},{CONTEXT:'production',BRANCH:''},{CONTEXT:'production'},
  {CONTEXT:'deploy-preview',BRANCH:TARGET_BRANCH},{CONTEXT:'branch-deploy',BRANCH:TARGET_BRANCH},{CONTEXT:'dev',BRANCH:TARGET_BRANCH},
  {CONTEXT:'Production',BRANCH:TARGET_BRANCH},{CONTEXT:'',BRANCH:TARGET_BRANCH},{BRANCH:TARGET_BRANCH},{}
];
const GUARD=`if [ "$CONTEXT" = "production" ] && [ "$BRANCH" = "${TARGET_BRANCH}" ]; then `;
const PRODUCTION_STEPS=['rm -rf dist','npm ci','npm run build','node scripts/netlify-headers.mjs'];

// The command's only deletion: the guard first, then exactly rm -rf dist as the first step, written statically (no
// variable, glob, quote, trailing slash or other path), and no other rm or deleting tool anywhere in the command.
function assertCleanupIsExactlyDist(command){
  assert.ok(command.startsWith(GUARD),'the guard runs before anything else');
  const [first,...rest]=command.slice(GUARD.length).split(' && ');
  assert.equal(first,'rm -rf dist','the first step after the guard removes exactly dist');
  assert.doesNotMatch(rest.join(' && '),/\b(?:rm|rmdir|unlink|find|git|mv)\b/,'nothing else is deleted');
}

// What each call of the production command does, done in-process inside a scratch copy of pool-platform: rm -rf dist
// removes that copy's dist/, npm ci is the installed tree, and the build and headers generator are the real ones with
// the SDK stand-in. A call with no equivalent here fails, so the replay follows the command as written.
async function replay(calls,app){
  const steps={
    'rm -rf dist':()=>fs.rmSync(path.join(app,'dist'),{recursive:true,force:true}),
    'npm ci':()=>{},
    'npm run build':()=>buildCommercialFrontend({appDir:app,env:LIVE,bundleSdk:async()=>SDK_STAND_IN}),
    'node scripts/netlify-headers.mjs':()=>writeNetlifyHeaders({appDir:app})
  };
  for(const call of calls){
    assert.ok(Object.hasOwn(steps,call),`no in-process equivalent for ${call}`);
    await steps[call]();
  }
}

test('netlify.toml holds exactly the reviewed settings: rm -rf dist, npm ci, the existing build, the headers generator, dist, netlify/functions, Pretty URLs off',()=>{
  assert.deepEqual(TOML,{
    build:{
      ignore:`if [ "$CONTEXT" = "production" ] && [ "$BRANCH" = "${TARGET_BRANCH}" ]; then exit 1; else exit 0; fi`,
      command:`if [ "$CONTEXT" = "production" ] && [ "$BRANCH" = "${TARGET_BRANCH}" ]; then rm -rf dist && npm ci && npm run build && node scripts/netlify-headers.mjs; else echo "Refusing to build: only a production deploy of ${TARGET_BRANCH} builds." >&2; exit 1; fi`,
      publish:'dist'
    },
    'build.processing.html':{pretty_urls:false},
    functions:{directory:'netlify/functions'}
  });
  // The existing build is the package's own build script, and the functions directory is outside the publish one.
  assert.equal(JSON.parse(read('package.json')).scripts.build,'node scripts/build.mjs');
  assert.ok(fs.statSync(path.join(HERE,TOML.functions.directory)).isDirectory());
  assert.equal(path.relative(path.join(HERE,TOML.build.publish),path.join(HERE,TOML.functions.directory)).startsWith('..'),true);
});

test('netlify.toml sets no environment value, URL, origin, secret, header rule, redirect or reference to main',()=>{
  const text=read('netlify.toml'),settings=text.split('\n').filter(line=>!line.trim().startsWith('#')).join('\n');
  assert.doesNotMatch(text,/^\s*\[\[/m,'no array of tables: no [[headers]], [[redirects]], [[plugins]] or [[edge_functions]]');
  assert.doesNotMatch(text,/^\s*\[(?:[a-z.]+\.)?(?:environment|context|headers|redirects|dev|plugins|images|edge_functions)\b/m,'no environment, context, header, redirect or plugin table');
  assert.doesNotMatch(text,/[a-z][a-z0-9+.-]*:\/\//i,'no URL, not even in a comment');
  assert.doesNotMatch(text,/\bmain\b/,'main is never named, let alone as a deployment source');
  assert.doesNotMatch(settings,/POOL_PLATFORM_|neon|apirest|localhost|\.test\b|\.app\b|\.com\b|secret|password|token|api[_-]?key|@/i,'no backend, origin or credential');
  assert.doesNotMatch(settings,/Content-Security-Policy|connect-src|default-src|Strict-Transport|Cache-Control|nosniff|Referrer/i,'response headers are generated into dist/_headers, never set here');
  assert.equal(Object.hasOwn(TOML.build,'base')||Object.hasOwn(TOML.build,'environment'),false,'the base directory is set on the site, and no variable is set here');
});

test('the deploy-context guard: only a production deploy of the candidate branch builds; main, other branches and every other context are skipped',t=>{
  // Netlify runs the ignore command with Bash: exit 1 builds, exit 0 skips.
  assert.equal(runCommand(t,TOML.build.ignore,ALLOWED).status,1,'the production deploy of the candidate branch builds');
  for(const env of REFUSED)assert.equal(runCommand(t,TOML.build.ignore,env).status,0,`skipped: ${JSON.stringify(env)}`);
});

test('the build command repeats the guard (an ignore command never cancels a build-hook build), then removes dist and runs npm ci, the build and the headers generator in order',t=>{
  const allowed=runCommand(t,TOML.build.command,ALLOWED);
  assert.deepEqual([allowed.status,allowed.calls],[0,PRODUCTION_STEPS]);
  // Refused before the cleanup: no rm, npm or node runs for any other branch or context.
  for(const env of REFUSED){
    const refusedRun=runCommand(t,TOML.build.command,env);
    assert.deepEqual([refusedRun.status,refusedRun.calls],[1,[]],`refused, nothing run: ${JSON.stringify(env)}`);
    assert.match(refusedRun.stderr,/Refusing to build: only a production deploy of commercial-v1-netlify-adapter builds\./);
  }
  // A failing step stops the chain: nothing is installed if dist could not be removed, nothing is built from an
  // install that failed, and no headers without a build.
  assert.deepEqual(runCommand(t,TOML.build.command,ALLOWED,{fail:'rm -rf'}),{status:7,stderr:'',calls:['rm -rf dist']});
  assert.deepEqual(runCommand(t,TOML.build.command,ALLOWED,{fail:'npm ci'}),{status:7,stderr:'',calls:['rm -rf dist','npm ci']});
  assert.deepEqual(runCommand(t,TOML.build.command,ALLOWED,{fail:'npm run'}),{status:7,stderr:'',calls:['rm -rf dist','npm ci','npm run build']});
  assert.deepEqual(runCommand(t,TOML.build.command,ALLOWED,{fail:'node scripts/netlify-headers.mjs'}),{status:7,stderr:'',calls:PRODUCTION_STEPS});
});

test('the cleanup target is statically exactly dist: no broader path, variable, glob or trailing slash, and nothing before the guard or in the ignore command',t=>{
  assertCleanupIsExactlyDist(TOML.build.command);
  assert.doesNotMatch(TOML.build.ignore,/\brm\b/,'the ignore command deletes nothing');
  // The check has teeth: each broadening, a cleanup moved before the guard or into the refusal, and a second one fail it.
  for(const target of ['.','*','$VARIABLE','dist/','"$SOME_DYNAMIC_VALUE"','"dist"','./dist','dist dist','../dist','/dist','~/dist','dist*']){
    const command=TOML.build.command.replace('rm -rf dist ',`rm -rf ${target} `);
    assert.notEqual(command,TOML.build.command);
    assert.throws(()=>assertCleanupIsExactlyDist(command),assert.AssertionError,target);
  }
  const early=`rm -rf dist; ${TOML.build.command.replace('rm -rf dist && ','')}`;
  for(const command of [early,TOML.build.command.replace('exit 1; fi','rm -rf dist; exit 1; fi'),
    TOML.build.command.replace('&& npm run build','&& rm -rf . && npm run build'),TOML.build.command.replace('npm ci &&','/bin/rm -rf dist && npm ci &&')]){
    assert.notEqual(command,TOML.build.command);
    assert.throws(()=>assertCleanupIsExactlyDist(command),assert.AssertionError,command);
  }
  // And the harness sees it: a cleanup before the guard would run for a refused deploy, where none may.
  assert.deepEqual(runCommand(t,early,REFUSED[0]).calls,['rm -rf dist']);
});

test('a warm working tree: the production command rebuilds over the previous deploy\'s dist/, _headers and a stale file included, to the same bytes as a clean build',async t=>{
  const app=path.join(scratch(t),'pool-platform'),dist=path.join(app,'dist');
  fs.mkdirSync(app);
  for(const name of STATIC_FILES)fs.copyFileSync(path.join(HERE,name),path.join(app,name));
  const {calls}=runCommand(t,TOML.build.command,ALLOWED);
  const published=()=>Object.fromEntries(listFiles(dist).map(name=>[name,sha256(fs.readFileSync(path.join(dist,name)))]));
  await replay(calls,app);
  const clean=published();
  assert.deepEqual(Object.keys(clean),[...OUTPUT_FILES,HEADERS_FILE].sort(),'a clean build');
  // Netlify's cache restores the previous working tree, generated dist/ and its _headers included.
  await replay(calls,app);
  assert.deepEqual(published(),clean,'a warm build publishes the clean build\'s bytes');
  fs.writeFileSync(path.join(dist,'stale.js'),'// from an older build\n');
  fs.mkdirSync(path.join(dist,'retired'));
  fs.writeFileSync(path.join(dist,'retired','page.html'),'<!-- removed from the allow-list -->\n');
  await replay(calls,app);
  assert.deepEqual(published(),clean,'a stale output file never survives into a new build');
  // The builders themselves still refuse that tree: only the hosting command's cleanup makes it buildable.
  fs.writeFileSync(path.join(dist,'stale.js'),'// from an older build\n');
  await assert.rejects(replay(calls.filter(call=>call!=='rm -rf dist'),app),/holds _headers, which this build does not produce/);
  assert.ok(fs.existsSync(path.join(dist,'stale.js'))&&fs.existsSync(path.join(dist,HEADERS_FILE)),'the refusing build deleted nothing');
});

test('.nvmrc pins Node 22 and nothing else',()=>{
  assert.equal(read('.nvmrc'),'22\n');
});

test('_headers: exact bytes for a live build, with the CSP scripts/serve.mjs sends for the same build, and the other four headers',async t=>{
  const dir=await built(t,LIVE);
  const result=writeNetlifyHeaders({dir});
  const text=fs.readFileSync(path.join(dir,HEADERS_FILE),'utf8');
  assert.equal(text,expectedHeaders('live',LIVE_CSP));
  assert.deepEqual(result,{dir,mode:'live',csp:LIVE_CSP,bytes:Buffer.byteLength(text),sha256:sha256(text)});
  // The same derivation as the local server, from the built configuration and nothing else.
  assert.equal(result.csp,contentSecurityPolicy(parseRuntimeConfig(fs.readFileSync(path.join(dir,'platform-config.js'),'utf8'))));
  const server=await startServer({dir,port:0,log:()=>{},env:PROXY});
  t.after(()=>server.close());
  assert.equal(server.csp,result.csp,'what Netlify serves is what the localhost gate served');
  for(const directive of ["connect-src 'self' https://ep-example-000000.apirest.c-0.us-east-2.aws.neon.test","frame-ancestors 'none'","script-src 'self'","base-uri 'none'"]){
    assert.ok(result.csp.split('; ').includes(directive),directive);
  }
  assert.doesNotMatch(text,/neonauth|unsafe-|\*\.|data:|blob:/);
  // Only the build's own files plus _headers: the one hosting artifact added after the build.
  assert.deepEqual(listFiles(dir),[...OUTPUT_FILES,HEADERS_FILE].sort());
});

test('_headers: a sandbox build gets its own CSP, connect-src \'self\' only, and says it is the sandbox; live and sandbox differ only there',async t=>{
  const sandbox=await built(t,{}),live=await built(t,LIVE);
  const s=writeNetlifyHeaders({dir:sandbox}),l=writeNetlifyHeaders({dir:live});
  assert.equal(fs.readFileSync(path.join(sandbox,HEADERS_FILE),'utf8'),expectedHeaders('sandbox',SANDBOX_CSP));
  assert.deepEqual([s.mode,s.csp,l.mode],['sandbox',SANDBOX_CSP,'live']);
  assert.match(s.csp,/; connect-src 'self'; /);
  const [a,b]=[sandbox,live].map(dir=>fs.readFileSync(path.join(dir,HEADERS_FILE),'utf8').split('\n'));
  assert.deepEqual(a.map((line,i)=>line===b[i]?null:i).filter(i=>i!==null),[0,2],'only the comment and the CSP line differ');
  // The mode comes from the built configuration only, never from this process's environment.
  assert.deepEqual(netlifyHeaders(runtimeConfigFromEnv({})),expectedHeaders('sandbox',SANDBOX_CSP));
  assert.deepEqual(netlifyHeaders(runtimeConfigFromEnv(LIVE)),expectedHeaders('live',LIVE_CSP));
  assert.doesNotMatch(GENERATOR_CODE,/process\.env|\benv\b/,'the generator reads no environment variable');
});

test('_headers: same build, same bytes, and the SHA-256 reported is the file\'s own; the CLI prints it',async t=>{
  const one=await built(t,LIVE),two=await built(t,LIVE);
  const a=writeNetlifyHeaders({dir:one}),b=writeNetlifyHeaders({dir:two});
  assert.ok(fs.readFileSync(path.join(one,HEADERS_FILE)).equals(fs.readFileSync(path.join(two,HEADERS_FILE))));
  assert.equal(a.sha256,b.sha256);
  assert.equal(a.sha256,sha256(fs.readFileSync(path.join(one,HEADERS_FILE))));
  const three=await built(t,LIVE);
  const cli=spawnSync(process.execPath,[path.join(HERE,'scripts/netlify-headers.mjs'),'--dir',three],{encoding:'utf8'});
  assert.equal(cli.status,0,cli.stderr);
  assert.ok(cli.stdout.includes(`${a.sha256}  ${String(a.bytes).padStart(7)}  ${HEADERS_FILE}`),cli.stdout);
  assert.ok(cli.stdout.includes(`Content-Security-Policy: ${LIVE_CSP}`));
  assert.match(cli.stdout,/the live build/);
  const again=spawnSync(process.execPath,[path.join(HERE,'scripts/netlify-headers.mjs'),'--dir',three],{encoding:'utf8'});
  assert.equal(again.status,1,'run twice, the second run refuses');
  assert.match(again.stderr,/already holds _headers/);
  const usage=spawnSync(process.execPath,[path.join(HERE,'scripts/netlify-headers.mjs'),'--out',three],{encoding:'utf8'});
  assert.equal(usage.status,2);
});

test('_headers never names Neon Auth: a Data API URL on a Neon Auth host is refused, and the generator never reads the Auth upstream',async t=>{
  const misconfigured=await built(t,{...LIVE,POOL_PLATFORM_DATA_URL:AUTH});
  refused(misconfigured,/Neon Auth/,'a Data API URL on a Neon Auth host');
  for(const host of ['ep-x.neonauth.c-0.us-east-2.aws.neon.tech','ep-x.NEONAUTH.c-0.us-east-2.aws.neon.tech','neonauth.example.test']){
    const config={mode:'live',dataUrl:`https://${host.toLowerCase()}/neondb/rest/v1`,defaultPoolSlug:''};
    assert.throws(()=>netlifyHeaders(config),/Neon Auth/,host);
  }
  assert.doesNotMatch(GENERATOR_CODE,/AUTH_UPSTREAM|auth-proxy-core|netlify-adapter/,'the generator knows nothing of the proxy or its upstream');
  // CSP construction is not duplicated: the generator only calls the shared contentSecurityPolicy().
  assert.doesNotMatch(GENERATOR_CODE,/-src|frame-ancestors|base-uri|form-action/,'no CSP directive is written in the generator');
  assert.match(GENERATOR_CODE,/^import \{[^}]*\bcontentSecurityPolicy\b[^}]*\bparseRuntimeConfig\b[^}]*\} from '\.\/runtime-config\.mjs';$/m);
});

test('_headers carries no credential or secret: server-only settings and stray secrets in the build environment never reach it',async t=>{
  const env={...LIVE,...PROXY,POOL_PLATFORM_APP_ORIGIN:'https://pools.example.test',POOL_PLATFORM_PASSWORD:'hunter2-secret',
    DATABASE_URL:'postgresql://owner:hunter2-secret@ep-x.c-0.us-east-2.aws.neon.tech/neondb',NEON_API_KEY:'napi_secret_value'};
  const dir=await built(t,env);
  const saved={...process.env};
  Object.assign(process.env,env);
  try{writeNetlifyHeaders({dir})}finally{for(const key of Object.keys(env))if(saved[key]===undefined)delete process.env[key];else process.env[key]=saved[key]}
  const text=fs.readFileSync(path.join(dir,HEADERS_FILE),'utf8');
  assert.equal(text,expectedHeaders('live',LIVE_CSP),'the environment changes nothing');
  for(const secret of ['hunter2','secret','napi_','postgresql','owner','pools.example.test',AUTH,new URL(AUTH).host,'neonauth','@','Bearer','Authorization','Cookie']){
    assert.equal(text.toLowerCase().includes(secret.toLowerCase()),false,secret);
  }
  assert.deepEqual(text.split('\n').filter(line=>line.startsWith('  ')).map(line=>line.trim().split(':')[0]),
    ['Content-Security-Policy','X-Content-Type-Options','Referrer-Policy','Cache-Control','Strict-Transport-Security']);
});

test('_headers is refused for missing or malformed build output: no directory, a file, a hand-edited configuration, an altered SDK bundle',async t=>{
  const root=scratch(t);
  refused(path.join(root,'missing'),/not a build directory/,'missing');
  fs.writeFileSync(path.join(root,'file'),'x');
  assert.throws(()=>writeNetlifyHeaders({dir:path.join(root,'file')}),/not a build directory/);
  const empty=path.join(root,'empty');fs.mkdirSync(empty);
  refused(empty,/is not exactly the build's output/,'empty');
  const edited=await built(t,LIVE);
  fs.appendFileSync(path.join(edited,'platform-config.js'),'globalThis.pwned=1;\n');
  refused(edited,ConfigError,'hand-edited platform-config.js');
  const named=await built(t,LIVE);
  fs.writeFileSync(path.join(named,'platform-config.js'),fs.readFileSync(path.join(named,'platform-config.js'),'utf8').replace('{"mode"',`{"authUrl":"${AUTH}","mode"`));
  refused(named,ConfigError,'a configuration naming Neon Auth');
  refused(await built(t,LIVE,'export function createClient(){}\n'),/Neon SDK bundle/,'an SDK bundle without its version record');
  refused(await built(t,LIVE,`${SDK_STAND_IN}import("https://cdn.jsdelivr.net/npm/x");\n`),/Neon SDK bundle/,'an SDK bundle that imports from a CDN');
});

test('_headers is refused for a stale or unexpected dist layout: a changed page, a missing file, an extra file, server code, a symbolic link',async t=>{
  const stale=await built(t,LIVE);
  fs.appendFileSync(path.join(stale,'participant.html'),'<!-- older build -->\n');
  refused(stale,/participant\.html differs from/,'a page from another build');
  const script=await built(t,{});
  fs.writeFileSync(path.join(script,'service-worker.js'),'// an older worker\n');
  refused(script,/service-worker\.js differs from/,'a stale worker');
  const missing=await built(t,LIVE);
  fs.rmSync(path.join(missing,'styles.css'));
  refused(missing,/missing styles\.css/,'a missing file');
  for(const extra of ['stale.js','index.html.bak','api/auth.mjs','server/auth-proxy-core.mjs','server/netlify-adapter.mjs','netlify/functions/auth-otp.mjs',
    'netlify.toml','.nvmrc','vercel.json','scripts/netlify-headers.mjs','_redirects','.env','vendor/other.js']){
    const dir=await built(t,LIVE);
    fs.mkdirSync(path.dirname(path.join(dir,extra)),{recursive:true});
    fs.writeFileSync(path.join(dir,extra),'x');
    refused(dir,new RegExp(`unexpected ${extra.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}`),extra);
  }
  const linked=await built(t,LIVE);
  fs.rmSync(path.join(linked,'styles.css'));
  fs.symlinkSync(path.join(HERE,'styles.css'),path.join(linked,'styles.css'));
  refused(linked,/styles\.css \(not a regular file\)/,'a symbolic link in place of a built file');
});

test('an existing _headers is never overwritten, whatever it holds, and a symbolic link there is never followed',async t=>{
  for(const body of ['/*\n  Content-Security-Policy: default-src *\n','',null]){
    const dir=await built(t,LIVE);
    if(body===null){
      // Written by an earlier run: the same bytes this run would write are still refused.
      writeNetlifyHeaders({dir});
      refused(dir,/already holds _headers/,'an earlier run');
    }else{
      fs.writeFileSync(path.join(dir,HEADERS_FILE),body);
      refused(dir,/already holds _headers/,JSON.stringify(body));
    }
  }
  const dir=await built(t,LIVE),target=path.join(scratch(t),'elsewhere');
  fs.symlinkSync(target,path.join(dir,HEADERS_FILE));
  assert.throws(()=>writeNetlifyHeaders({dir}),/_headers/);
  assert.equal(fs.existsSync(target),false,'nothing was written through the link');
});

test('the build refuses to replace a dist/ that holds _headers, so a stale hosting file can never survive a rebuild',async t=>{
  const app=path.join(scratch(t),'pool-platform'),dist=path.join(app,'dist');
  fs.mkdirSync(app);
  for(const name of fs.readdirSync(HERE))if(/\.(?:html|css|js|webmanifest)$/.test(name))fs.copyFileSync(path.join(HERE,name),path.join(app,name));
  await buildCommercialFrontend({appDir:app,env:LIVE,bundleSdk:async()=>SDK_STAND_IN});
  writeNetlifyHeaders({appDir:app});
  assert.deepEqual(listFiles(dist),[...OUTPUT_FILES,HEADERS_FILE].sort(),'appDir/dist is the default');
  await assert.rejects(buildCommercialFrontend({appDir:app,env:LIVE,bundleSdk:async()=>SDK_STAND_IN}),/holds _headers, which this build does not produce/);
  assert.ok(fs.existsSync(path.join(dist,HEADERS_FILE)),'nothing was deleted');
  assert.equal(path.join(APP_DIR,'dist'),path.join(HERE,'dist'),'the default build directory is pool-platform/dist, Netlify\'s publish directory');
});

describe('the real Neon SDK bundle',{skip:ESBUILD?false:'run npm ci in pool-platform to bundle the real SDK'},()=>{
  test('a real live build passes every check, and the only file added is _headers with the build\'s CSP',async t=>{
    const dir=path.join(scratch(t),'dist');
    await buildCommercialFrontend({outDir:dir,env:LIVE});
    const result=writeNetlifyHeaders({dir});
    assert.equal(fs.readFileSync(path.join(dir,HEADERS_FILE),'utf8'),expectedHeaders('live',LIVE_CSP));
    assert.equal(result.mode,'live');
    assert.deepEqual(listFiles(dir),[...OUTPUT_FILES,HEADERS_FILE].sort());
  });
});
